/**
 * Studio Service Catalog — raw seed data (temporary location).
 *
 * RAW_SERVICE_CATALOG lives here until a future physical split into seeds/core-services.ts,
 * seeds/retired.ts, and seeds/bundles.ts (deferred — Phase 5+). New seeds belong in the
 * split files once that work lands. Do not add new permanent service logic here.
 *
 * Normalized v3 export: `@/catalog/seeds` (SERVICE_CATALOG).
 */

import type {
  BillingType,
  DeliveryMapping,
  DiscoveryMappingRule,
  ExecutionMode,
  LaunchStatus,
  MonthlyCycleWindow,
  ProductionLane,
  ServiceCategoryId,
  ServiceClass,
  ServiceFamilyId,
  ServiceId,
  ServiceTimingWindow,
  StudioServiceEntry,
} from "@/catalog/types";
import { CATALOG_SCHEMA_VERSION } from "@/catalog/types";
import { ROUTE_MAP_LAUNCH_SERVICES } from "@/catalog/route-map-launch";
import { ROUTE_MAP_V2_ALL_SERVICES } from "@/catalog/route-map-v2-launch";

function withDiscoverySync(
  mapping: readonly DiscoveryMappingRule[],
): Pick<StudioServiceEntry, "discoveryMapping" | "discoveryTriggers"> {
  return { discoveryMapping: mapping, discoveryTriggers: mapping };
}

const QUICK_FIRST: ServiceTimingWindow = {
  minDays: 3,
  maxDays: 5,
  label: "3–5 business days",
};
const QUICK_FINAL: ServiceTimingWindow = {
  minDays: 5,
  maxDays: 8,
  label: "5–8 business days",
};
const STANDARD_FIRST: ServiceTimingWindow = {
  minDays: 6,
  maxDays: 8,
  label: "6–8 business days",
};
const STANDARD_FINAL: ServiceTimingWindow = {
  minDays: 12,
  maxDays: 17,
  label: "12–17 business days",
};
const COMPLEX_FIRST: ServiceTimingWindow = {
  minDays: 8,
  maxDays: 11,
  label: "8–11 business days",
};
const COMPLEX_FINAL: ServiceTimingWindow = {
  minDays: 18,
  maxDays: 24,
  label: "18–24 business days",
};

const REVISION_ONE_TIME = "One consolidated revision round.";
const REVISION_MONTHLY = "One consolidated revision round across the monthly batch.";

/** Green / yellow / red rollout — only `active` SKUs are client-visible. */
const LAUNCH_STATUS_BY_ID: Readonly<Record<ServiceId, LaunchStatus>> = {
  // Green — active (8)
  "bf-001": "active",
  "sm-001": "active",
  "sm-001-monthly": "active",
  "em-001": "active",
  "em-001-monthly": "active",
  "cc-001": "active",
  "ma-001": "active",
  "ap-001": "active",
  // Yellow — limited (11)
  "bf-002": "limited",
  "cp-001": "limited",
  "mo-001": "limited",
  "ma-001-monthly": "limited",
  "mo-001-monthly": "limited",
  "social_media-execution": "limited",
  "social_media-execution-monthly": "limited",
  "email_marketing-execution": "limited",
  "email_marketing-execution-monthly": "limited",
  "sms_marketing-execution": "limited",
  "sms_marketing-execution-monthly": "limited",
  // Red — paused (9)
  "cp-001-monthly": "paused",
  "sms-001": "paused",
  "sms-001-monthly": "paused",
  "cc-001-monthly": "paused",
  "cc-002": "paused",
  "cc-002-monthly": "paused",
  "vp-001": "paused",
  "vp-001-monthly": "paused",
  "lp-001": "paused",
  // Legacy retired packages
  spark: "retired",
  momentum: "retired",
  growth: "retired",
  "email-marketing": "retired",
  "sms-campaign": "retired",
  "business-workflow": "retired",
  "customer-follow-up": "retired",
  "monthly-support": "retired",
  // Route Map V1 launch — limited (front-door checkout only, not Discovery green set)
  "rm-j001": "retired",
  "rm-j002": "limited",
  "rm-j003": "retired",
  "rm-j004": "retired",
  "rm-j005": "limited",
  "rm-j006": "retired",
  "rm-j007": "limited",
  "rm-j008": "limited",
  // Route Map V2 activated RTU shelf + post/publish add-on
  "v2-rtu-flyer": "limited",
  "v2-rtu-menu": "limited",
  "v2-rtu-service-sheet": "limited",
  "v2-rtu-social-posts": "limited",
  "v2-rtu-promotion-graphics": "limited",
  "v2-rtu-email-kit": "limited",
  "v2-rtu-sms-kit": "limited",
  "v2-rtu-voice": "limited",
  "v2-rtu-short-video": "limited",
  "v2-rtu-business-card": "limited",
  "v2-addon-post-publish": "retired",
};

function resolveLaunchStatus(id: ServiceId): LaunchStatus {
  return LAUNCH_STATUS_BY_ID[id];
}

type V2ServiceSeed = {
  id: ServiceId;
  familyId: ServiceFamilyId;
  name: string;
  category: ServiceCategoryId;
  serviceClass: ServiceClass;
  billingType: BillingType;
  priceCents: number;
  productionLane: ProductionLane;
  firstReviewWindow: ServiceTimingWindow;
  finalDeliveryWindow?: ServiceTimingWindow;
  monthlyCycleWindow?: MonthlyCycleWindow;
  purpose: string;
  deliverables: readonly string[];
  exclusions: readonly string[];
  revisionRule: string;
  clientResponsibilities: readonly string[];
  executionMode: ExecutionMode;
  requiresClientAccess: boolean;
  requiresClientMaterials: boolean;
  isRecommendable: boolean;
  isAddable: boolean;
  deliveryMapping: DeliveryMapping;
  discoveryMapping?: readonly DiscoveryMappingRule[];
  customerReceives?: string;
  internalProductionNotes?: string;
  includedRevisionRounds?: number;
};

/** Shared discovery rules — v2 SKU mapping per approved billing rules (Slice 4). */
const DM_SITUATION_STARTING: DiscoveryMappingRule = {
  signal: "situation",
  value: "Starting fresh",
  weight: 2,
};
const DM_SITUATION_GROWING: DiscoveryMappingRule = {
  signal: "situation",
  value: "Trying to stay visible more consistently",
  weight: 1,
};
const DM_SITUATION_PIVOTING: DiscoveryMappingRule = {
  signal: "situation",
  value: "Refreshing how my business looks",
  weight: 2,
};
const DM_SITUATION_SCALING: DiscoveryMappingRule = {
  signal: "situation",
  value: "Promoting an offer, event, sale, or launch",
  weight: 2,
};
const DM_CHALLENGE_CLARITY: DiscoveryMappingRule = {
  signal: "challenge",
  value: "I am not sure what to say about my business",
  weight: 2,
};
const DM_CHALLENGE_VISIBILITY: DiscoveryMappingRule = {
  signal: "challenge",
  value: "I need help promoting something",
  weight: 2,
};
const DM_CHALLENGE_OPS: DiscoveryMappingRule = {
  signal: "challenge",
  value: "I do not have time to create marketing content",
  weight: 1,
};
const DM_CHALLENGE_TEAM: DiscoveryMappingRule = {
  signal: "challenge",
  value: "I am not showing up consistently online",
  weight: 1,
};
const DM_NEED_CUSTOMERS: DiscoveryMappingRule = {
  signal: "need",
  value: "get-more-customers",
  weight: 2,
};
const DM_NEED_BRANDING: DiscoveryMappingRule = {
  signal: "need",
  value: "better-branding",
  weight: 2,
};
const DM_NEED_CONTENT: DiscoveryMappingRule = {
  signal: "need",
  value: "create-content",
  weight: 2,
};
const DM_NEED_COMMUNICATION: DiscoveryMappingRule = {
  signal: "need",
  value: "improve-communication",
  weight: 2,
};
const DM_NEED_SYSTEMS: DiscoveryMappingRule = {
  signal: "need",
  value: "better-business-systems",
  weight: 2,
};
const DM_NEED_WORKFLOW: DiscoveryMappingRule = {
  signal: "need",
  value: "workflow-improvements",
  weight: 2,
};
const DM_NEED_EXPERIENCE: DiscoveryMappingRule = {
  signal: "need",
  value: "better-customer-experience",
  weight: 2,
};
const DM_FOCUS_BRAND: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "brand",
  tileId: "your-focus",
  weight: 2,
};
const DM_FOCUS_MARKETING: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "marketing",
  tileId: "your-focus",
  weight: 2,
};
const DM_FOCUS_CONTENT: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "content",
  tileId: "your-focus",
  weight: 2,
};
const DM_FOCUS_CUSTOMER: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "customer",
  tileId: "your-focus",
  weight: 2,
};
const DM_FOCUS_OPERATIONS: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "operations",
  tileId: "your-focus",
  weight: 2,
};
const DM_FOCUS_SALES: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "sales",
  tileId: "your-focus",
  weight: 2,
};
const DM_FOCUS_LAUNCH: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "launch",
  tileId: "your-focus",
  weight: 2,
};
const DM_FOCUS_CONSISTENT: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "consistent",
  tileId: "your-focus",
  weight: 2,
};
const DM_CHALLENGE_TECHNOLOGY: DiscoveryMappingRule = {
  signal: "challenge",
  value: "My business does not look polished or consistent",
  weight: 2,
};
const DM_TOOLS_NONE: DiscoveryMappingRule = {
  signal: "tools",
  value: "None yet / starting from scratch",
  tileId: "your-current-tools",
  weight: 2,
};
const DM_TOOLS_OUTDATED: DiscoveryMappingRule = {
  signal: "tools",
  value: "My branding looks inconsistent",
  tileId: "whats-slowing-you-down",
  weight: 2,
};
const DM_FOCUS_ONGOING: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "ongoing",
  tileId: "your-focus",
  weight: 2,
};
const DM_TOOLS_EMAIL: DiscoveryMappingRule = {
  signal: "tools",
  value: "Email list or email platform",
  tileId: "your-current-tools",
  weight: 3,
};
const DM_TOOLS_CRM: DiscoveryMappingRule = {
  signal: "tools",
  value: "CRM (HubSpot, Salesforce, etc.)",
  tileId: "your-current-tools",
  weight: 2,
};
const DM_SUCCESS_ENGAGEMENT: DiscoveryMappingRule = {
  signal: "tools",
  value: "More consistent social media visibility",
  tileId: "success-looks-like",
  weight: 2,
};
const DM_SUCCESS_SAVING_TIME: DiscoveryMappingRule = {
  signal: "tools",
  value: "Spending less time creating and posting marketing",
  tileId: "success-looks-like",
  weight: 2,
};
const DM_SLOWING_INCONSISTENT: DiscoveryMappingRule = {
  signal: "tools",
  value: "My branding looks inconsistent",
  tileId: "whats-slowing-you-down",
  weight: 2,
};
const DM_ANYTHING_VIDEO: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "video",
  tileId: "anything-else",
  weight: 2,
};
const DM_ANYTHING_AUDIO: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "audio",
  tileId: "anything-else",
  weight: 2,
};
const DM_ANYTHING_VOICE: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "voice",
  tileId: "anything-else",
  weight: 2,
};
const DM_ANYTHING_NARRATION: DiscoveryMappingRule = {
  signal: "focus-keyword",
  value: "narration",
  tileId: "anything-else",
  weight: 2,
};

const REVISION_EXECUTION =
  "No separate revision round — executes materials approved through the matching parent service.";

const EXECUTION_ADDON_CLIENT_RESPONSIBILITIES = [
  "Client owns platform subscriptions, contact permissions, consent, compliance, and message usage fees",
  "Client must approve materials before scheduled publication or sending",
  "No legal or compliance review is provided by The Studio",
] as const;

type V2ExecutionAddOnSeed = {
  id: ServiceId;
  familyId: ServiceFamilyId;
  name: string;
  parentServiceId: ServiceId;
  billingType: BillingType;
  priceCents: number;
  productionLane: ProductionLane;
  firstReviewWindow: ServiceTimingWindow;
  finalDeliveryWindow?: ServiceTimingWindow;
  monthlyCycleWindow?: MonthlyCycleWindow;
  purpose: string;
  deliverables: readonly string[];
  exclusions: readonly string[];
  executionChannel: "social" | "email" | "sms";
  deliveryItemKey: string;
};

function v2ExecutionAddOn(seed: V2ExecutionAddOnSeed): StudioServiceEntry {
  const fulfillmentMode = seed.billingType === "monthly" ? "monthly_cycle" : "project";
  return {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    id: seed.id,
    familyId: seed.familyId,
    name: seed.name,
    category: "add-on-services",
    serviceClass: "essential",
    dependencies: [seed.parentServiceId],
    includedRevisionRounds: 0,
    canSubstitute: false,
    addOnEligible: true,
    upgradeEligible: false,
    deliveryFormats: [],
    minimumCustomerRequirements: [...EXECUTION_ADDON_CLIENT_RESPONSIBILITIES],
    recommendedCustomerRequirements: [],
    serviceStatus: "active",
    status: "active",
    billingType: seed.billingType,
    priceCents: seed.priceCents,
    productionLane: seed.productionLane,
    firstReviewWindow: seed.firstReviewWindow,
    finalDeliveryWindow: seed.finalDeliveryWindow,
    monthlyCycleWindow: seed.monthlyCycleWindow,
    purpose: seed.purpose,
    deliverables: seed.deliverables,
    exclusions: seed.exclusions,
    revisionRule: REVISION_EXECUTION,
    clientResponsibilities: EXECUTION_ADDON_CLIENT_RESPONSIBILITIES,
    executionMode: "managed_execution_when_selected",
    requiresClientAccess: true,
    requiresClientMaterials: false,
    isRecommendable: false,
    isAddable: false,
    launchStatus: resolveLaunchStatus(seed.id),
    serviceGuideFaq: [],
    deliveryMapping: {
      fulfillmentMode,
      executionChannel: seed.executionChannel,
      items: [{ key: seed.deliveryItemKey, quantity: 1, unit: "execution" }],
    },
    isExecutionAddOn: true,
    eligibleParentFamilyIds: [seed.familyId],
    discoveryTriggers: [],
    discoveryMapping: [],
  };
}

function v2Service(seed: V2ServiceSeed): StudioServiceEntry {
  return {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    id: seed.id,
    familyId: seed.familyId,
    name: seed.name,
    category: seed.category,
    serviceClass: seed.serviceClass,
    customerReceives: seed.customerReceives,
    internalProductionNotes: seed.internalProductionNotes,
    dependencies: [],
    includedRevisionRounds: seed.includedRevisionRounds ?? 1,
    canSubstitute: true,
    addOnEligible: true,
    upgradeEligible: true,
    deliveryFormats: [],
    minimumCustomerRequirements: [...seed.clientResponsibilities],
    recommendedCustomerRequirements: [],
    serviceStatus: "active",
    status: "active",
    billingType: seed.billingType,
    priceCents: seed.priceCents,
    productionLane: seed.productionLane,
    firstReviewWindow: seed.firstReviewWindow,
    finalDeliveryWindow: seed.finalDeliveryWindow,
    monthlyCycleWindow: seed.monthlyCycleWindow,
    purpose: seed.purpose,
    deliverables: seed.deliverables,
    exclusions: seed.exclusions,
    revisionRule: seed.revisionRule,
    clientResponsibilities: seed.clientResponsibilities,
    executionMode: seed.executionMode,
    requiresClientAccess: seed.requiresClientAccess,
    requiresClientMaterials: seed.requiresClientMaterials,
    isRecommendable: seed.isRecommendable,
    isAddable: seed.isAddable,
    launchStatus: resolveLaunchStatus(seed.id),
    serviceGuideFaq: [],
    deliveryMapping: seed.deliveryMapping,
    ...withDiscoverySync(seed.discoveryMapping ?? []),
  };
}

const V2_LAUNCH_SERVICES: readonly StudioServiceEntry[] = [
  v2Service({
    id: "bf-001",
    familyId: "brand_identity",
    name: "Brand Identity Refresh",
    category: "brand-foundation",
    serviceClass: "signature",
    billingType: "one_time",
    priceCents: 49500,
    productionLane: "standard_build",
    firstReviewWindow: STANDARD_FIRST,
    finalDeliveryWindow: STANDARD_FINAL,
    purpose:
      "For a business with an existing name and visual starting point that needs a cleaner, more consistent marketing presentation.",
    deliverables: [
      "Reviews current logo, colors, fonts, and visible marketing materials",
      "Refines a color palette with usable HEX codes",
      "Recommends font pairings",
      "Provides existing-logo usage guidance: acceptable color, background, spacing, and consistency rules",
      "Creates a one-page Brand Direction Sheet",
      "Creates one branded profile image or cover graphic",
    ],
    exclusions: [
      "New logo creation from scratch",
      "Multiple logo concepts",
      "Naming",
      "Trademark/legal work",
      "Full website redesign",
      "Photography",
      "Printing",
      "A full social package",
      "Editable source files by default",
      "Unlimited revisions",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Existing logo files if available",
      "Correct business name",
      "Current branding references",
      "Examples of what they like/dislike",
      "Accurate business information",
      "Timely feedback",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "project",
      items: [
        { key: "brand_direction_sheet", quantity: 1, unit: "document" },
        { key: "profile_or_cover_graphic", quantity: 1, unit: "graphic" },
        { key: "color_palette", quantity: 1, unit: "palette" },
        { key: "font_pairing_recommendation", quantity: 1, unit: "recommendation" },
        { key: "logo_usage_guidance", quantity: 1, unit: "guide" },
      ],
    },
    discoveryMapping: [
      DM_SITUATION_STARTING,
      DM_SITUATION_PIVOTING,
      DM_CHALLENGE_CLARITY,
      DM_CHALLENGE_TECHNOLOGY,
      DM_TOOLS_NONE,
      DM_NEED_BRANDING,
      DM_FOCUS_BRAND,
    ],
  }),
  v2Service({
    id: "bf-002",
    familyId: "brand_messaging",
    name: "Brand Messaging",
    category: "brand-foundation",
    serviceClass: "signature",
    billingType: "one_time",
    priceCents: 59500,
    productionLane: "standard_build",
    firstReviewWindow: STANDARD_FIRST,
    finalDeliveryWindow: STANDARD_FINAL,
    purpose:
      "For businesses that need clearer language for explaining what they do, who they help, and why customers should choose them.",
    deliverables: [
      "Reviews current public-facing business language",
      "Creates one clear value proposition",
      "Creates one target-customer focus statement",
      "Creates one positioning statement",
      "Creates one core brand message",
      "Defines three message pillars",
      "Writes one short business description",
      "Writes one About paragraph",
      "Provides up to three tagline or headline options",
      "Provides tone-of-voice guidance",
      "Delivers a Brand Messaging Guide",
    ],
    exclusions: [
      "Naming/renaming",
      "Full website copy",
      "Landing-page copy",
      "Blog articles",
      "Social captions",
      "Email or SMS campaigns",
      "Sales scripts",
      "Competitor research",
      "Legal/compliance review",
      "Unlimited taglines",
      "Unlimited revisions",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Accurate business, service, offer, and customer information",
      "Existing messaging if available",
      "Required/forbidden words or claims",
      "Timely feedback",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "project",
      items: [{ key: "brand_messaging_guide", quantity: 1, unit: "document" }],
    },
    discoveryMapping: [
      DM_SITUATION_STARTING,
      DM_SITUATION_PIVOTING,
      DM_CHALLENGE_CLARITY,
      DM_CHALLENGE_TECHNOLOGY,
      DM_TOOLS_NONE,
      { signal: "need", value: "better-branding", weight: 3 },
      DM_FOCUS_BRAND,
    ],
  }),
  v2Service({
    id: "cp-001",
    familyId: "campaign",
    name: "Campaign Launch Kit",
    category: "campaign-services",
    serviceClass: "signature",
    billingType: "one_time",
    priceCents: 89500,
    productionLane: "complex_build",
    firstReviewWindow: COMPLEX_FIRST,
    finalDeliveryWindow: COMPLEX_FINAL,
    purpose:
      "For one launch, offer, event, service, promotion, seasonal push, reopening, or awareness campaign.",
    deliverables: [
      "Defines one campaign goal and one audience focus",
      "Creates one campaign message and call to action",
      "Creates one campaign theme or hook",
      "Produces a creative direction board",
      "Recommends selected channels to support the campaign",
      "Creates one rollout outline",
      "Provides up to three campaign concept directions",
      "Refines one selected direction after feedback",
    ],
    exclusions: [
      "Social posts",
      "Email campaigns",
      "SMS campaigns",
      "Flyers/assets",
      "Video",
      "Landing-page copy/build",
      "Paid ads",
      "Ad spend",
      "Media buying",
      "PR",
      "Influencers",
      "Ongoing campaign management",
      "Unlimited concepts",
      "Guaranteed outcomes",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Exact offer, pricing, dates, discount terms",
      "Business facts",
      "Brand materials",
      "Required disclosures",
      "Timely feedback",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "project",
      items: [
        { key: "campaign_concept_directions", quantity: 3, unit: "concepts" },
        { key: "creative_direction_board", quantity: 1, unit: "board" },
        { key: "rollout_outline", quantity: 1, unit: "outline" },
      ],
    },
    discoveryMapping: [
      DM_SITUATION_STARTING,
      DM_NEED_CUSTOMERS,
      DM_CHALLENGE_VISIBILITY,
      DM_CHALLENGE_CLARITY,
      DM_CHALLENGE_TECHNOLOGY,
      DM_TOOLS_NONE,
      DM_FOCUS_MARKETING,
      DM_FOCUS_LAUNCH,
      DM_FOCUS_SALES,
    ],
  }),
  v2Service({
    id: "cp-001-monthly",
    familyId: "campaign",
    name: "Monthly Campaign Support",
    category: "campaign-services",
    serviceClass: "signature",
    billingType: "monthly",
    priceCents: 34900,
    productionLane: "ongoing_monthly",
    firstReviewWindow: STANDARD_FIRST,
    monthlyCycleWindow: {
      label:
        "First monthly direction 6–8 business days after inputs are complete; later cycles follow the monthly production calendar.",
    },
    purpose:
      "For a business that wants one defined monthly campaign focus and coordination direction for selected Studio services.",
    deliverables: [
      "Creates one monthly campaign focus",
      "Creates one monthly campaign message and CTA",
      "Creates one theme/creative direction",
      "Provides one rollout recommendation",
      "Coordinates direction for selected Studio services",
      "Provides one refinement round on campaign direction",
    ],
    exclusions: [
      "Automatic production of social, email, SMS, video, assets, or landing pages",
      "Paid-media management",
      "Daily management",
      "Full campaign rebuilds",
      "Guaranteed results",
    ],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [
      "Current monthly offer, dates, inventory/service facts",
      "Channel priorities",
      "Timely approval",
    ],
    executionMode: "strategy_direction",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "monthly_cycle",
      items: [{ key: "monthly_campaign_direction", quantity: 1, unit: "direction" }],
    },
    discoveryMapping: [
      DM_SITUATION_GROWING,
      DM_SITUATION_SCALING,
      DM_NEED_CUSTOMERS,
      DM_NEED_CONTENT,
      DM_NEED_WORKFLOW,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_MARKETING,
      DM_FOCUS_ONGOING,
      DM_FOCUS_CONSISTENT,
    ],
  }),
  v2Service({
    id: "sm-001",
    familyId: "social_media",
    name: "Social Media Launch Set",
    category: "social-media",
    serviceClass: "signature",
    billingType: "one_time",
    priceCents: 39500,
    productionLane: "standard_build",
    firstReviewWindow: STANDARD_FIRST,
    finalDeliveryWindow: STANDARD_FINAL,
    purpose:
      "A polished starter batch of social content for one offer, launch, event, or business focus.",
    deliverables: [
      "Creates one content/campaign focus",
      "Creates up to six static social posts",
      "Writes one caption per post",
      "Provides suggested posting order",
      "Provides basic hashtag/keyword suggestions where appropriate",
      "Provides a simple content calendar",
    ],
    exclusions: [
      "Daily posting",
      "Community/DM/comment management",
      "Paid ads",
      "Filming/photography",
      "Reels/advanced motion",
      "Multiple aspect-ratio versions",
      "Unlimited hashtag research",
      "Guaranteed reach/followers/results",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Connected social-account access if execution is selected",
      "Correct offer details",
      "Logos/images/source materials",
      "Timely approval",
    ],
    executionMode: "managed_execution_when_selected",
    requiresClientAccess: true,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "project",
      executionChannel: "social",
      items: [
        { key: "static_social_post", quantity: 6, unit: "posts" },
        { key: "content_calendar", quantity: 1, unit: "calendar" },
      ],
    },
    discoveryMapping: [
      DM_SITUATION_STARTING,
      DM_SITUATION_GROWING,
      DM_NEED_CUSTOMERS,
      DM_NEED_CONTENT,
      DM_NEED_EXPERIENCE,
      DM_CHALLENGE_VISIBILITY,
      DM_CHALLENGE_TECHNOLOGY,
      DM_TOOLS_NONE,
      DM_FOCUS_CONTENT,
      DM_FOCUS_MARKETING,
    ],
  }),
  v2Service({
    id: "sm-001-monthly",
    familyId: "social_media",
    name: "Monthly Social Media Content Support",
    category: "social-media",
    serviceClass: "signature",
    billingType: "monthly",
    priceCents: 34900,
    productionLane: "ongoing_monthly",
    firstReviewWindow: STANDARD_FIRST,
    monthlyCycleWindow: {
      label:
        "First batch 6–8 business days after direction/materials are complete; later batches follow the monthly production calendar.",
    },
    purpose: "Consistent client-ready social content around one monthly business focus.",
    deliverables: [
      "Creates one monthly content focus",
      "Creates up to six branded static social posts",
      "Writes captions for each post",
      "Provides suggested sequence",
      "Provides a simple monthly posting calendar",
    ],
    exclusions: [
      "Daily engagement",
      "Comments/DMs/inbox management",
      "Paid ads",
      "Reels/video",
      "Photography/filming",
      "Unlimited requests",
      "Extra posts",
      "Multiple formats per post",
      "Performance guarantees",
    ],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [
      "One connected client-owned social account for managed execution",
      "Approved monthly offer/materials",
      "Timely approval",
    ],
    executionMode: "managed_execution_when_selected",
    requiresClientAccess: true,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "monthly_cycle",
      executionChannel: "social",
      items: [
        { key: "static_social_post", quantity: 6, unit: "posts" },
        { key: "monthly_posting_calendar", quantity: 1, unit: "calendar" },
      ],
    },
    discoveryMapping: [
      DM_SITUATION_GROWING,
      DM_SITUATION_SCALING,
      DM_NEED_CONTENT,
      DM_NEED_COMMUNICATION,
      DM_NEED_WORKFLOW,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_CONTENT,
      DM_FOCUS_CONSISTENT,
      DM_FOCUS_ONGOING,
    ],
  }),
  v2Service({
    id: "em-001",
    familyId: "email_marketing",
    name: "Email Campaign Build",
    category: "email-marketing",
    serviceClass: "core",
    billingType: "one_time",
    priceCents: 32500,
    productionLane: "standard_build",
    firstReviewWindow: STANDARD_FIRST,
    finalDeliveryWindow: STANDARD_FINAL,
    purpose:
      "One defined launch, offer, event, promotion, follow-up, or customer re-engagement email campaign.",
    deliverables: [
      "Defines one campaign goal",
      "Writes up to two client-ready marketing emails",
      "Provides subject-line options and preview text for each email",
      "Writes CTAs and provides simple branded layout/content direction",
      "Provides suggested sending order/timing",
    ],
    exclusions: [
      "List building/buying/cleaning",
      "Segmentation",
      "Automation",
      "Custom HTML coding",
      "Platform setup",
      "CRM integration",
      "Deliverability troubleshooting",
      "More than two emails",
      "Guaranteed performance",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Connected email-platform access if execution is selected",
      "Accurate links, offers, dates, permissions, subscriber data, factual claims, and approval",
    ],
    executionMode: "managed_execution_when_selected",
    requiresClientAccess: true,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "project",
      executionChannel: "email",
      items: [{ key: "marketing_email", quantity: 2, unit: "emails" }],
    },
    discoveryMapping: [
      DM_TOOLS_EMAIL,
      DM_TOOLS_CRM,
      DM_FOCUS_CUSTOMER,
    ],
  }),
  v2Service({
    id: "em-001-monthly",
    familyId: "email_marketing",
    name: "Monthly Email Content Support",
    category: "email-marketing",
    serviceClass: "core",
    billingType: "monthly",
    priceCents: 22500,
    productionLane: "ongoing_monthly",
    firstReviewWindow: STANDARD_FIRST,
    monthlyCycleWindow: {
      label:
        "First batch 6–8 business days after direction/materials are complete; later batches follow the monthly production calendar.",
    },
    purpose: "Consistent promotional/customer communication without the client writing every email.",
    deliverables: [
      "Creates one monthly email focus",
      "Writes up to two client-ready emails per month",
      "Provides subject-line options, preview text, CTA, and simple layout direction",
      "Suggests send timing",
    ],
    exclusions: [
      "Automation",
      "Segmentation",
      "List growth",
      "Platform fees",
      "Custom HTML",
      "Daily requests",
      "Extra emails",
      "Performance guarantees",
    ],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [
      "Client-owned email-platform access",
      "Valid consented list",
      "Accurate links/offer details",
      "Approval",
    ],
    executionMode: "managed_execution_when_selected",
    requiresClientAccess: true,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "monthly_cycle",
      executionChannel: "email",
      items: [{ key: "marketing_email", quantity: 2, unit: "emails" }],
    },
    discoveryMapping: [
      DM_TOOLS_EMAIL,
      DM_SUCCESS_SAVING_TIME,
      DM_FOCUS_ONGOING,
      DM_FOCUS_CONSISTENT,
    ],
  }),
  v2Service({
    id: "sms-001",
    familyId: "sms_marketing",
    name: "SMS Campaign Build",
    category: "sms-marketing",
    serviceClass: "core",
    billingType: "one_time",
    priceCents: 17500,
    productionLane: "quick_turn",
    firstReviewWindow: QUICK_FIRST,
    finalDeliveryWindow: QUICK_FINAL,
    purpose:
      "One promotion, event, reminder sequence, offer, launch, or customer follow-up campaign.",
    deliverables: [
      "Defines one campaign goal",
      "Writes up to four client-ready SMS messages",
      "Provides suggested sending order/timing",
      "Writes a clear CTA in each message",
      "Uses character-conscious SMS copy",
    ],
    exclusions: [
      "Platform setup",
      "List/contact management",
      "Consent collection",
      "Opt-out handling",
      "Automation",
      "MMS graphics/video",
      "More than four messages",
      "Legal compliance review",
      "Guaranteed results",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Connected SMS-platform access if execution is selected",
      "Confirmation of recipient consent",
      "Accurate offer details and links",
      "Approval",
    ],
    executionMode: "managed_execution_when_selected",
    requiresClientAccess: true,
    requiresClientMaterials: false,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "project",
      executionChannel: "sms",
      items: [{ key: "sms_message", quantity: 4, unit: "messages" }],
    },
    discoveryMapping: [
      DM_NEED_CUSTOMERS,
      DM_NEED_COMMUNICATION,
      DM_NEED_EXPERIENCE,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_CUSTOMER,
      DM_FOCUS_SALES,
    ],
  }),
  v2Service({
    id: "sms-001-monthly",
    familyId: "sms_marketing",
    name: "Monthly SMS Content Support",
    category: "sms-marketing",
    serviceClass: "core",
    billingType: "monthly",
    priceCents: 14900,
    productionLane: "ongoing_monthly",
    firstReviewWindow: QUICK_FIRST,
    monthlyCycleWindow: {
      label:
        "First batch 3–5 business days after direction is confirmed; later batches follow the monthly production calendar.",
    },
    purpose: "A controlled recurring sequence of promotional or reminder SMS messages.",
    deliverables: [
      "Creates one monthly messaging focus",
      "Writes up to four client-ready SMS messages per month",
      "Provides suggested sequence and CTAs",
    ],
    exclusions: [
      "Sending without approved connected platform/access",
      "Platform fees",
      "Automation",
      "Consent records",
      "Opt-out management",
      "Daily/unlimited requests",
      "MMS",
      "Performance guarantees",
    ],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [
      "Valid consented contacts",
      "Platform access",
      "Accurate offer details",
      "Timely approval",
    ],
    executionMode: "managed_execution_when_selected",
    requiresClientAccess: true,
    requiresClientMaterials: false,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "monthly_cycle",
      executionChannel: "sms",
      items: [{ key: "sms_message", quantity: 4, unit: "messages" }],
    },
    discoveryMapping: [
      DM_SITUATION_GROWING,
      DM_SITUATION_SCALING,
      DM_NEED_COMMUNICATION,
      DM_NEED_WORKFLOW,
      DM_NEED_EXPERIENCE,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_ONGOING,
    ],
  }),
  v2Service({
    id: "cc-001",
    familyId: "marketing_copywriting",
    name: "Marketing Copywriting Project",
    category: "content-copywriting",
    serviceClass: "signature",
    billingType: "one_time",
    priceCents: 22500,
    productionLane: "quick_turn",
    firstReviewWindow: QUICK_FIRST,
    finalDeliveryWindow: QUICK_FINAL,
    purpose: "Short promotional copy for one defined marketing goal.",
    deliverables: [
      "Writes up to three short-form copy assets",
      "Writes up to 750 total words",
      "Provides headlines and calls to action where appropriate",
    ],
    exclusions: [
      "Full website/landing-page copy",
      "Email or SMS campaigns",
      "Blog articles",
      "Brand messaging strategy",
      "Naming/tagline projects",
      "Legal/compliance review",
      "More than three assets",
      "More than 750 words",
      "Same-day work",
      "Unlimited revisions",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Accurate offer, price, deadline, links, product/service facts",
      "Required language",
      "Approval",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "project",
      items: [{ key: "short_form_copy_asset", quantity: 3, unit: "assets" }],
    },
    discoveryMapping: [
      DM_FOCUS_CONTENT,
      DM_SUCCESS_ENGAGEMENT,
      DM_SLOWING_INCONSISTENT,
    ],
  }),
  v2Service({
    id: "cc-001-monthly",
    familyId: "marketing_copywriting",
    name: "Monthly Copy Support",
    category: "content-copywriting",
    serviceClass: "signature",
    billingType: "monthly",
    priceCents: 24900,
    productionLane: "ongoing_monthly",
    firstReviewWindow: QUICK_FIRST,
    monthlyCycleWindow: {
      label:
        "First batch 3–5 business days after requests/materials are complete; later work follows the agreed monthly request calendar.",
    },
    purpose: "A controlled monthly batch of smaller promotional copy needs.",
    deliverables: [
      "Completes up to four short-form copy requests per month",
      "Writes up to 1,000 total words per month",
      "Includes headlines and CTAs where appropriate",
    ],
    exclusions: [
      "Full website rewrites",
      "Landing-page copy",
      "Emails/SMS unless separately selected",
      "Blog articles",
      "Unlimited/drip requests",
      "Rush work",
      "More than four requests",
      "More than 1,000 words",
      "Legal review",
      "Guaranteed results",
    ],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [
      "Batched requests in the agreed request window",
      "Accurate factual/offer details",
      "Timely approval",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "monthly_cycle",
      items: [{ key: "short_form_copy_request", quantity: 4, unit: "requests" }],
    },
    discoveryMapping: [
      DM_SITUATION_GROWING,
      DM_SITUATION_SCALING,
      DM_NEED_CONTENT,
      DM_NEED_WORKFLOW,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_CONTENT,
      DM_FOCUS_ONGOING,
    ],
  }),
  v2Service({
    id: "cc-002",
    familyId: "content_writing",
    name: "Content Writing Project",
    category: "content-copywriting",
    serviceClass: "core",
    billingType: "one_time",
    priceCents: 42500,
    productionLane: "standard_build",
    firstReviewWindow: STANDARD_FIRST,
    finalDeliveryWindow: STANDARD_FINAL,
    purpose: "One educational, trust-building, or authority-building content piece.",
    deliverables: [
      "Writes one long-form content piece, up to 1,200 words",
      "Creates one headline and structured section headings",
      "Aligns to one client-approved topic/audience",
      "Provides basic keyword/topic alignment from the client's stated focus",
      "Includes one CTA",
    ],
    exclusions: [
      "Interviews/investigative research",
      "Website publishing",
      "Design/formatting",
      "Full SEO strategy",
      "Multi-article packages",
      "Legal/regulatory review",
      "More than 1,200 words",
      "Unlimited revisions",
      "Guaranteed traffic/rankings/results",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Approved topic",
      "Accurate business and factual information",
      "Required sources",
      "Approval",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "project",
      items: [{ key: "long_form_content_piece", quantity: 1, unit: "piece" }],
    },
    discoveryMapping: [
      DM_SITUATION_GROWING,
      DM_NEED_CONTENT,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_CONTENT,
    ],
  }),
  v2Service({
    id: "cc-002-monthly",
    familyId: "content_writing",
    name: "Monthly Content Writing Support",
    category: "content-copywriting",
    serviceClass: "core",
    billingType: "monthly",
    priceCents: 59500,
    productionLane: "ongoing_monthly",
    firstReviewWindow: STANDARD_FIRST,
    monthlyCycleWindow: {
      label:
        "First batch 6–8 business days after topics/materials are complete; later content follows the monthly production calendar.",
    },
    purpose: "Consistent educational or trust-building written content.",
    deliverables: [
      "Writes up to two long-form content pieces per month",
      "Each piece is up to 1,000 words",
      "Creates headline, structure, CTA, and basic topic alignment",
    ],
    exclusions: [
      "Website publishing",
      "SEO management",
      "Backlink outreach",
      "Research requiring interviews/outside investigation",
      "More than two pieces",
      "More than 1,000 words each",
      "Daily requests",
      "Unlimited revisions",
      "Guaranteed rankings/traffic/results",
    ],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [
      "Approved monthly topics",
      "Accurate source material",
      "Factual review",
      "Timely feedback",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "monthly_cycle",
      items: [{ key: "long_form_content_piece", quantity: 2, unit: "pieces" }],
    },
    discoveryMapping: [
      DM_SITUATION_GROWING,
      DM_SITUATION_SCALING,
      DM_NEED_CONTENT,
      DM_NEED_WORKFLOW,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_CONTENT,
      DM_FOCUS_ONGOING,
    ],
  }),
  v2Service({
    id: "vp-001",
    familyId: "marketing_video",
    name: "Marketing Video Project",
    category: "video-production",
    serviceClass: "signature",
    billingType: "one_time",
    priceCents: 79500,
    productionLane: "complex_build",
    firstReviewWindow: COMPLEX_FIRST,
    finalDeliveryWindow: COMPLEX_FINAL,
    purpose:
      "One short-form video for a campaign, service, offer, event, launch, or social promotion.",
    deliverables: [
      "Creates one video up to 60 seconds",
      "Uses one format only: vertical, square, or landscape",
      "Performs basic editing/pacing",
      "Adds branded text overlays, basic transitions, on-screen captions, and CTA treatment",
      "Delivers final MP4",
    ],
    exclusions: [
      "On-site filming",
      "Drone footage",
      "Photography",
      "Talent casting",
      "Advanced custom animation",
      "Multiple aspect ratios/cuts",
      "Video longer than 60 seconds",
      "Music licensing outside approved tools",
      "Paid placement",
      "Guaranteed results",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Usable organized footage/photos/logo/source materials",
      "Correct offer details",
      "Required claims",
      "Approval",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "project",
      items: [{ key: "marketing_video", quantity: 1, unit: "mp4" }],
    },
    discoveryMapping: [
      DM_SITUATION_STARTING,
      DM_SITUATION_GROWING,
      DM_NEED_CONTENT,
      DM_NEED_CUSTOMERS,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_CONTENT,
      DM_FOCUS_MARKETING,
      DM_FOCUS_LAUNCH,
    ],
  }),
  v2Service({
    id: "vp-001-monthly",
    familyId: "marketing_video",
    name: "Monthly Video Content Support",
    category: "video-production",
    serviceClass: "signature",
    billingType: "monthly",
    priceCents: 99500,
    productionLane: "ongoing_monthly",
    firstReviewWindow: COMPLEX_FIRST,
    monthlyCycleWindow: {
      label:
        "First batch 8–11 business days after materials are complete; later batches follow the monthly production calendar.",
    },
    purpose: "A limited recurring stream of short-form video content.",
    deliverables: [
      "Creates up to two videos per month",
      "Each video is up to 45 seconds",
      "Uses one approved monthly content focus",
      "Includes basic editing, branded overlays, captions, and CTA treatment",
      "Delivers final MP4 files",
    ],
    exclusions: [
      "Filming/photography",
      "Daily reels",
      "Multiple cuts/aspect ratios",
      "Advanced motion graphics",
      "Unlimited source-footage cleanup",
      "More than two videos",
      "More than 45 seconds each",
      "Guaranteed results",
    ],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [
      "Usable organized footage and required source materials before work begins",
      "Timely approval",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "monthly_cycle",
      items: [{ key: "marketing_video", quantity: 2, unit: "mp4" }],
    },
    discoveryMapping: [
      DM_SITUATION_GROWING,
      DM_SITUATION_SCALING,
      DM_NEED_CONTENT,
      DM_NEED_WORKFLOW,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_CONTENT,
      DM_FOCUS_ONGOING,
    ],
  }),
  v2Service({
    id: "ap-001",
    familyId: "ai_voice_over",
    name: "AI Voice Over Production",
    category: "audio-production",
    serviceClass: "core",
    billingType: "one_time",
    priceCents: 17500,
    productionLane: "quick_turn",
    firstReviewWindow: QUICK_FIRST,
    finalDeliveryWindow: QUICK_FINAL,
    purpose:
      "Narration for one marketing video, social clip, explainer, presentation, or campaign asset.",
    deliverables: [
      "Creates one AI-generated voice-over track",
      "Supports up to 300 script words",
      "Uses one approved voice style and one language",
      "Performs basic pacing/pronunciation review",
      "Delivers final MP3 or WAV",
    ],
    exclusions: [
      "Scriptwriting unless selected separately",
      "Voice cloning",
      "Celebrity/public-figure/recognizable-person imitation",
      "Human voice recording",
      "Multiple speakers/voices",
      "Translations",
      "Music production",
      "Advanced audio mixing",
      "More than 300 words",
      "Legal claim review",
      "Rights beyond the approved tool's terms",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Final script",
      "Pronunciation notes",
      "Accurate claims/names/offers",
      "Confirmation of rights to supplied content",
      "Approval",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "project",
      items: [{ key: "ai_voice_over_track", quantity: 1, unit: "audio" }],
    },
    discoveryMapping: [
      DM_FOCUS_CONTENT,
      { signal: "focus-keyword", value: "video", tileId: "your-focus", weight: 2 },
      DM_ANYTHING_VIDEO,
      DM_ANYTHING_AUDIO,
      DM_ANYTHING_VOICE,
      DM_ANYTHING_NARRATION,
    ],
  }),
  v2Service({
    id: "lp-001",
    familyId: "landing_page_content",
    name: "Landing Page Content & Creative Direction",
    category: "landing-pages-web-content",
    serviceClass: "signature",
    billingType: "one_time",
    priceCents: 89500,
    productionLane: "complex_build",
    firstReviewWindow: COMPLEX_FIRST,
    finalDeliveryWindow: COMPLEX_FINAL,
    purpose:
      "One focused page blueprint for a specific offer, service, event, promotion, campaign, or lead-generation goal.",
    deliverables: [
      "Defines one page goal and audience focus",
      "Creates a section-by-section page outline",
      "Writes up to 800 words of landing-page copy",
      "Writes headline, subhead, CTAs, and core section copy",
      "Recommends page structure and content flow",
      "Provides basic visual direction from approved brand materials",
      "Provides one mobile-aware layout recommendation",
    ],
    exclusions: [
      "Coding",
      "Platform publishing",
      "Hosting/domains/subscriptions",
      "Ecommerce",
      "Payment processing",
      "Forms",
      "CRM/integrations/automations",
      "Analytics/tracking",
      "SEO setup",
      "Full website redesign",
      "Multiple pages",
      "More than 800 words",
      "Custom web development",
      "Guaranteed conversions/rankings/results",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Exact offer, price, dates, links, disclosures",
      "Service/product facts",
      "Branding materials",
      "Platform limitations",
      "Approval",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    customerReceives:
      "Landing page copy and creative direction for marketing campaigns — not full website development, hosting, or ongoing site management.",
    internalProductionNotes:
      "LP-001 does not include website hosting, full website development, maintenance, DNS, or platform management.",
    deliveryMapping: {
      fulfillmentMode: "project",
      items: [
        { key: "landing_page_copy", quantity: 800, unit: "words" },
        { key: "page_outline", quantity: 1, unit: "document" },
        { key: "layout_recommendation", quantity: 1, unit: "recommendation" },
      ],
    },
    discoveryMapping: [
      DM_SITUATION_STARTING,
      DM_SITUATION_GROWING,
      DM_NEED_CUSTOMERS,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_MARKETING,
      DM_FOCUS_SALES,
      DM_FOCUS_LAUNCH,
      { signal: "focus-keyword", value: "conversion", tileId: "your-focus", weight: 2 },
    ],
  }),
  v2Service({
    id: "mo-001",
    familyId: "marketing_optimization",
    name: "Marketing Optimization Review",
    category: "marketing-optimization",
    serviceClass: "core",
    billingType: "one_time",
    priceCents: 39500,
    productionLane: "standard_build",
    firstReviewWindow: STANDARD_FIRST,
    finalDeliveryWindow: STANDARD_FINAL,
    purpose:
      "Review and practical improvement of existing marketing that feels unclear, inconsistent, outdated, or disconnected.",
    deliverables: [
      "Reviews up to three existing marketing assets or channels",
      "Identifies message, clarity, CTA, consistency, and customer-journey issues",
      "Gives prioritized improvement recommendations",
      "Revises up to two selected existing assets",
      "Provides a simple next-step action list",
    ],
    exclusions: [
      "Paid-ad account management",
      "Ad-platform optimization",
      "Full website audit",
      "SEO audit",
      "Analytics setup",
      "CRM cleanup",
      "Automation",
      "Deep conversion testing",
      "Unlimited rewrites",
      "Guaranteed performance",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Current materials",
      "The actual problem they want improved",
      "Any available customer/performance feedback",
      "Accurate business information",
      "Approval",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "project",
      items: [
        { key: "asset_review", quantity: 3, unit: "assets" },
        { key: "asset_refinement", quantity: 2, unit: "assets" },
        { key: "action_list", quantity: 1, unit: "list" },
      ],
    },
    discoveryMapping: [
      DM_SITUATION_GROWING,
      DM_SITUATION_PIVOTING,
      DM_CHALLENGE_VISIBILITY,
      DM_CHALLENGE_OPS,
      DM_CHALLENGE_TECHNOLOGY,
      DM_TOOLS_OUTDATED,
      DM_NEED_SYSTEMS,
      DM_FOCUS_MARKETING,
      DM_FOCUS_OPERATIONS,
    ],
  }),
  v2Service({
    id: "mo-001-monthly",
    familyId: "marketing_optimization",
    name: "Monthly Marketing Optimization Support",
    category: "marketing-optimization",
    serviceClass: "core",
    billingType: "monthly",
    priceCents: 34900,
    productionLane: "ongoing_monthly",
    firstReviewWindow: STANDARD_FIRST,
    monthlyCycleWindow: {
      label:
        "First review 6–8 business days after materials/observations are complete; later cycles follow the monthly production calendar.",
    },
    purpose: "Regular practical improvement support for materials already in use.",
    deliverables: [
      "Defines one monthly optimization focus",
      "Reviews up to two active assets or channels per month",
      "Performs up to two approved refinements per month",
      "Provides monthly recommendations on what to keep, simplify, adjust, or test",
    ],
    exclusions: [
      "Constant monitoring",
      "Daily reporting",
      "Paid-media management",
      "Ad spend",
      "Deep dashboards",
      "Website development",
      "SEO management",
      "Full campaign rebuilds",
      "Unlimited refinements",
      "Guaranteed improvement",
    ],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [
      "Current materials",
      "Relevant feedback/observations",
      "Clear improvement objective",
      "Accurate information",
      "Approval",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "monthly_cycle",
      items: [
        { key: "asset_review", quantity: 2, unit: "assets" },
        { key: "asset_refinement", quantity: 2, unit: "assets" },
      ],
    },
    discoveryMapping: [
      DM_SITUATION_GROWING,
      DM_SITUATION_SCALING,
      DM_NEED_SYSTEMS,
      DM_NEED_WORKFLOW,
      DM_CHALLENGE_OPS,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_OPERATIONS,
      DM_FOCUS_ONGOING,
    ],
  }),
  v2Service({
    id: "ma-001",
    familyId: "marketing_assets",
    name: "Promotion Pack",
    category: "marketing-assets",
    serviceClass: "essential",
    billingType: "one_time",
    priceCents: 49500,
    productionLane: "standard_build",
    firstReviewWindow: STANDARD_FIRST,
    finalDeliveryWindow: STANDARD_FINAL,
    purpose:
      "A focused set of branded visual pieces for one campaign, service, offer, event, or launch.",
    deliverables: [
      "Creates up to four branded standard-format marketing assets",
      "Uses one agreed business/campaign focus",
      "Uses approved brand materials",
      "Delivers final digital files in agreed formats",
    ],
    exclusions: [
      "Printing/shipping",
      "Photography",
      "Custom illustration",
      "Multi-page brochures/catalogs",
      "Packaging",
      "Website design",
      "Large-format signage",
      "Editable source files by default",
      "Multiple size/version sets",
      "More than four assets",
      "Unlimited revisions",
      "Guaranteed results",
    ],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [
      "Final copy",
      "Offer terms",
      "Dates",
      "Prices",
      "Links",
      "Logos",
      "Required wording",
      "Print requirements if printing",
      "Approval",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    customerReceives:
      "Examples include brochures, flyers, rack cards, menus, business cards, posters, presentation materials, and similar finished marketing assets.",
    deliveryMapping: {
      fulfillmentMode: "project",
      items: [{ key: "marketing_asset", quantity: 4, unit: "assets" }],
    },
    discoveryMapping: [
      DM_SITUATION_GROWING,
      DM_NEED_CUSTOMERS,
      DM_NEED_BRANDING,
      DM_NEED_CONTENT,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_LAUNCH,
      DM_FOCUS_MARKETING,
    ],
  }),
  v2Service({
    id: "ma-001-monthly",
    familyId: "marketing_assets",
    name: "Monthly Marketing Asset Support",
    category: "marketing-assets",
    serviceClass: "essential",
    billingType: "monthly",
    priceCents: 44900,
    productionLane: "ongoing_monthly",
    firstReviewWindow: STANDARD_FIRST,
    monthlyCycleWindow: {
      label:
        "First batch 6–8 business days after direction/materials are complete; later batches follow the monthly production calendar.",
    },
    purpose: "A controlled recurring stream of smaller branded marketing pieces.",
    deliverables: [
      "Creates up to four standard-format branded assets per month",
      "Uses one monthly campaign, offer, event, or business focus",
      "Uses approved existing brand direction",
      "Delivers final digital files in agreed formats",
    ],
    exclusions: [
      "Unlimited requests",
      "Printing/shipping",
      "Photography/custom illustration",
      "Website work",
      "Full branding",
      "Complex multi-page/oversized collateral",
      "Editable source files by default",
      "More than four assets",
      "Unlimited revisions",
      "Guaranteed results",
    ],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [
      "Accurate final content",
      "Prices",
      "Dates",
      "Links",
      "Logos",
      "Required wording",
      "Approval",
    ],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: true,
    isAddable: true,
    deliveryMapping: {
      fulfillmentMode: "monthly_cycle",
      items: [{ key: "marketing_asset", quantity: 4, unit: "assets" }],
    },
    discoveryMapping: [
      DM_SITUATION_GROWING,
      DM_SITUATION_SCALING,
      DM_NEED_CONTENT,
      DM_NEED_WORKFLOW,
      DM_CHALLENGE_VISIBILITY,
      DM_FOCUS_ONGOING,
      DM_FOCUS_CONSISTENT,
    ],
  }),
  v2ExecutionAddOn({
    id: "social_media-execution",
    familyId: "social_media",
    name: "Social Scheduling & Publishing",
    parentServiceId: "sm-001",
    billingType: "one_time",
    priceCents: 10000,
    productionLane: "quick_turn",
    firstReviewWindow: QUICK_FIRST,
    finalDeliveryWindow: QUICK_FINAL,
    purpose:
      "Schedules and publishes only the included approved social posts from the matching parent service to one connected client-owned social account.",
    deliverables: [
      "Schedules and publishes included approved social posts from Social Media Launch Set (sm-001)",
      "Uses one connected client-owned social account",
    ],
    exclusions: [
      "Account setup",
      "Comments",
      "DMs",
      "Engagement",
      "Reporting",
      "Paid ads",
      "Extra formats",
      "Same-day changes",
      "Additional posts",
    ],
    executionChannel: "social",
    deliveryItemKey: "social_scheduling_publishing",
  }),
  v2ExecutionAddOn({
    id: "social_media-execution-monthly",
    familyId: "social_media",
    name: "Social Scheduling & Publishing",
    parentServiceId: "sm-001-monthly",
    billingType: "monthly",
    priceCents: 15000,
    productionLane: "ongoing_monthly",
    firstReviewWindow: STANDARD_FIRST,
    monthlyCycleWindow: {
      label:
        "Scheduling follows the monthly production calendar after parent-service materials are approved.",
    },
    purpose:
      "Schedules and publishes only the included approved social posts from the matching parent service to one connected client-owned social account.",
    deliverables: [
      "Schedules and publishes included approved social posts from Monthly Social Media Content Support (sm-001-monthly)",
      "Uses one connected client-owned social account each monthly cycle",
    ],
    exclusions: [
      "Account setup",
      "Comments",
      "DMs",
      "Engagement",
      "Reporting",
      "Paid ads",
      "Extra formats",
      "Same-day changes",
      "Additional posts",
    ],
    executionChannel: "social",
    deliveryItemKey: "social_scheduling_publishing",
  }),
  v2ExecutionAddOn({
    id: "email_marketing-execution",
    familyId: "email_marketing",
    name: "Email Scheduling & Sending",
    parentServiceId: "em-001",
    billingType: "one_time",
    priceCents: 7500,
    productionLane: "quick_turn",
    firstReviewWindow: QUICK_FIRST,
    finalDeliveryWindow: QUICK_FINAL,
    purpose:
      "Schedules and sends only the included approved emails from the matching parent service through one connected client-owned email platform.",
    deliverables: [
      "Schedules and sends included approved emails from Email Campaign Build (em-001)",
      "Uses one connected client-owned email platform",
    ],
    exclusions: [
      "List cleaning",
      "Segmentation",
      "Automations",
      "Platform setup",
      "Deliverability repair",
      "Extra emails",
      "Reply management",
    ],
    executionChannel: "email",
    deliveryItemKey: "email_scheduling_sending",
  }),
  v2ExecutionAddOn({
    id: "email_marketing-execution-monthly",
    familyId: "email_marketing",
    name: "Email Scheduling & Sending",
    parentServiceId: "em-001-monthly",
    billingType: "monthly",
    priceCents: 10000,
    productionLane: "ongoing_monthly",
    firstReviewWindow: STANDARD_FIRST,
    monthlyCycleWindow: {
      label:
        "Scheduling follows the monthly production calendar after parent-service materials are approved.",
    },
    purpose:
      "Schedules and sends only the included approved emails from the matching parent service through one connected client-owned email platform.",
    deliverables: [
      "Schedules and sends included approved emails from Monthly Email Content Support (em-001-monthly)",
      "Uses one connected client-owned email platform each monthly cycle",
    ],
    exclusions: [
      "List cleaning",
      "Segmentation",
      "Automations",
      "Platform setup",
      "Deliverability repair",
      "Extra emails",
      "Reply management",
    ],
    executionChannel: "email",
    deliveryItemKey: "email_scheduling_sending",
  }),
  v2ExecutionAddOn({
    id: "sms_marketing-execution",
    familyId: "sms_marketing",
    name: "SMS Scheduling & Sending",
    parentServiceId: "sms-001",
    billingType: "one_time",
    priceCents: 5000,
    productionLane: "quick_turn",
    firstReviewWindow: QUICK_FIRST,
    finalDeliveryWindow: QUICK_FINAL,
    purpose:
      "Schedules and sends only the included approved SMS messages from the matching parent service through one connected client-owned SMS platform.",
    deliverables: [
      "Schedules and sends included approved SMS messages from SMS Campaign Build (sms-001)",
      "Uses one connected client-owned SMS platform",
    ],
    exclusions: [
      "Contact management",
      "Consent collection",
      "Opt-out handling",
      "Automations",
      "MMS",
      "Reply management",
      "Platform setup",
      "Extra messages",
    ],
    executionChannel: "sms",
    deliveryItemKey: "sms_scheduling_sending",
  }),
  v2ExecutionAddOn({
    id: "sms_marketing-execution-monthly",
    familyId: "sms_marketing",
    name: "SMS Scheduling & Sending",
    parentServiceId: "sms-001-monthly",
    billingType: "monthly",
    priceCents: 7500,
    productionLane: "ongoing_monthly",
    firstReviewWindow: QUICK_FIRST,
    monthlyCycleWindow: {
      label:
        "Scheduling follows the monthly production calendar after parent-service materials are approved.",
    },
    purpose:
      "Schedules and sends only the included approved SMS messages from the matching parent service through one connected client-owned SMS platform.",
    deliverables: [
      "Schedules and sends included approved SMS messages from Monthly SMS Content Support (sms-001-monthly)",
      "Uses one connected client-owned SMS platform each monthly cycle",
    ],
    exclusions: [
      "Contact management",
      "Consent collection",
      "Opt-out handling",
      "Automations",
      "MMS",
      "Reply management",
      "Platform setup",
      "Extra messages",
    ],
    executionChannel: "sms",
    deliveryItemKey: "sms_scheduling_sending",
  }),
  ...ROUTE_MAP_LAUNCH_SERVICES,
  ...ROUTE_MAP_V2_ALL_SERVICES,
];

const LEGACY_RETIRED_SERVICES: readonly StudioServiceEntry[] = [
  {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    id: "spark",
    familyId: "campaign",
    name: "SPARK",
    category: "campaign-services",
    customerProblemSolved:
      "One-time campaign package for testing a promotion, product, event, or offer before investing in a larger marketing system.",
    customerReceives:
      "Campaign concepts, social posts, emails, SMS messages, marketing calendar, and video scripts.",
    serviceClass: "essential",
    dependencies: [],
    includedRevisionRounds: 1,
    canSubstitute: false,
    addOnEligible: false,
    upgradeEligible: true,
    deliveryFormats: [
      "campaign-package",
      "social-posts",
      "email-sequence",
      "sms-messages",
      "marketing-calendar",
      "video-scripts",
    ],
    minimumCustomerRequirements: ["Clear offer or promotion to market"],
    recommendedCustomerRequirements: [
      "Brand basics established",
      "Approved channels for email and SMS",
    ],
    internalProductionNotes: "1 revision round included. Full refund before work begins.",
    serviceStatus: "retired",
    billingType: "one_time",
    priceCents: 29900,
    productionLane: "standard_build",
    firstReviewWindow: STANDARD_FIRST,
    finalDeliveryWindow: STANDARD_FINAL,
    purpose: "Retired package — see Campaign Launch Kit (cp-001).",
    deliverables: [],
    exclusions: [],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: false,
    isAddable: false,
    launchStatus: "retired",
    serviceGuideFaq: [],
    deliveryMapping: { fulfillmentMode: "project", items: [] },
    customerDescription:
      "One-time campaign package for testing a promotion, product, event, or offer before investing in a larger marketing system.",
    internalDescription:
      "Entry package — full campaign asset set with minimal revision scope. Primary funnel for first-time customers.",
    legacyDeliverables: [
      { id: "concepts", label: "Campaign Concepts", quantity: 3, quotaId: "concepts" },
      { id: "social", label: "Social Media Posts", quantity: 3, quotaId: "social" },
      { id: "emails", label: "Marketing Emails", quantity: 3, quotaId: "emails" },
      { id: "sms", label: "SMS Messages", quantity: 3, quotaId: "sms" },
      { id: "calendar", label: "Marketing Calendar", quantity: 1, quotaId: "calendar" },
      { id: "video", label: "Video Scripts", quantity: 1, quotaId: "video" },
    ],
    pricing: { display: "$299", amountUsd: 299, billing: "one-time" },
    estimatedProductionTime: {
      customerLabel: "First concepts delivered within 7 business days",
      businessDays: 7,
    },
    productionEffort: { tier: "medium", hoursEstimate: 12 },
    ...withDiscoverySync([
      { signal: "need", value: "get-more-customers", weight: 2 },
      { signal: "situation", value: "Starting fresh", weight: 2 },
      { signal: "challenge", value: "Lack of clarity or direction", weight: 1 },
      { signal: "focus-keyword", value: "test", tileId: "your-focus", weight: 2 },
      { signal: "focus-keyword", value: "first campaign", tileId: "your-focus", weight: 2 },
    ]),
    productionNotes: "1 revision round included. Full refund before work begins.",
    status: "inactive",
  },
  {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    id: "momentum",
    familyId: "campaign",
    name: "MOMENTUM",
    category: "campaign-services",
    customerProblemSolved:
      "Monthly marketing support for businesses that want consistent visibility and regular content creation.",
    customerReceives:
      "Monthly campaign concepts, expanded social, email, and SMS quotas, calendar, and video scripts.",
    serviceClass: "core",
    dependencies: [],
    includedRevisionRounds: 1,
    canSubstitute: false,
    addOnEligible: false,
    upgradeEligible: true,
    deliveryFormats: [
      "campaign-package",
      "social-posts",
      "email-sequence",
      "sms-messages",
      "marketing-calendar",
      "video-scripts",
    ],
    minimumCustomerRequirements: ["Active marketing channels"],
    recommendedCustomerRequirements: [
      "Content approval workflow in place",
      "Monthly campaign theme or focus",
    ],
    internalProductionNotes: "1 revision round per monthly cycle. Refund before monthly work begins.",
    serviceStatus: "retired",
    billingType: "monthly",
    priceCents: 49900,
    productionLane: "ongoing_monthly",
    firstReviewWindow: STANDARD_FIRST,
    monthlyCycleWindow: {
      label: "First concepts delivered within 7 business days",
    },
    purpose: "Retired package — see Monthly Campaign Support (cp-001-monthly).",
    deliverables: [],
    exclusions: [],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [],
    executionMode: "strategy_direction",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: false,
    isAddable: false,
    launchStatus: "retired",
    serviceGuideFaq: [],
    deliveryMapping: { fulfillmentMode: "monthly_cycle", items: [] },
    customerDescription:
      "Monthly marketing support for businesses that want consistent visibility and regular content creation.",
    internalDescription:
      "Recurring revenue package — monthly deliverable quotas, same production SLA as SPARK per cycle.",
    legacyDeliverables: [
      { id: "concepts", label: "Campaign Concepts", quantity: 3, quotaId: "concepts" },
      { id: "social", label: "Social Media Posts", quantity: 6, quotaId: "social" },
      { id: "emails", label: "Marketing Emails", quantity: 6, quotaId: "emails" },
      { id: "sms", label: "SMS Messages", quantity: 6, quotaId: "sms" },
      { id: "calendar", label: "Marketing Calendar", quantity: 1, quotaId: "calendar" },
      { id: "video", label: "Video Scripts", quantity: 2, quotaId: "video" },
    ],
    pricing: { display: "$499 per month", amountUsd: 499, billing: "monthly" },
    estimatedProductionTime: {
      customerLabel: "First concepts delivered within 7 business days",
      businessDays: 7,
    },
    productionEffort: { tier: "high", hoursEstimate: 20 },
    ...withDiscoverySync([
      { signal: "need", value: "create-content", weight: 2 },
      { signal: "need", value: "improve-communication", weight: 1 },
      { signal: "situation", value: "Growing an existing business", weight: 2 },
      { signal: "challenge", value: "Marketing and visibility", weight: 2 },
      { signal: "focus-keyword", value: "consistent", tileId: "your-focus", weight: 2 },
      { signal: "focus-keyword", value: "monthly", tileId: "your-focus", weight: 2 },
    ]),
    productionNotes: "1 revision round per monthly cycle. Refund before monthly work begins.",
    status: "inactive",
  },
  {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    id: "growth",
    familyId: "campaign",
    name: "GROWTH",
    category: "campaign-services",
    customerProblemSolved:
      "Done-with-you partnership for businesses ready to build a complete marketing system instead of one-off campaigns.",
    customerReceives:
      "Highest deliverable quotas, quarterly strategy session, priority production queue, and expanded revision scope.",
    serviceClass: "signature",
    dependencies: [],
    includedRevisionRounds: 3,
    canSubstitute: false,
    addOnEligible: false,
    upgradeEligible: false,
    deliveryFormats: [
      "campaign-package",
      "social-posts",
      "email-sequence",
      "sms-messages",
      "marketing-calendar",
      "video-scripts",
      "strategy-session",
    ],
    minimumCustomerRequirements: ["Established business with growth goals"],
    recommendedCustomerRequirements: [
      "Dedicated point of contact for approvals",
      "Multi-channel marketing footprint",
    ],
    internalProductionNotes:
      "3 revision rounds included. Quarterly strategy session scheduled by ops.",
    serviceStatus: "retired",
    billingType: "monthly",
    priceCents: 79900,
    productionLane: "ongoing_monthly",
    firstReviewWindow: STANDARD_FIRST,
    monthlyCycleWindow: {
      label: "First concepts delivered within 7 business days",
    },
    purpose: "Retired package — not replaced by a single v2 SKU.",
    deliverables: [],
    exclusions: [],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [],
    executionMode: "strategy_direction",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: false,
    isAddable: false,
    launchStatus: "retired",
    serviceGuideFaq: [],
    deliveryMapping: { fulfillmentMode: "monthly_cycle", items: [] },
    customerDescription:
      "Done-with-you partnership for businesses ready to build a complete marketing system instead of one-off campaigns.",
    internalDescription:
      "Premium tier — highest quotas, strategy session, priority queue, 3 revision rounds.",
    legacyDeliverables: [
      { id: "concepts", label: "Campaign Concepts", quantity: 3, quotaId: "concepts" },
      { id: "social", label: "Social Media Posts", quantity: 10, quotaId: "social" },
      { id: "emails", label: "Marketing Emails", quantity: 10, quotaId: "emails" },
      { id: "sms", label: "SMS Messages", quantity: 10, quotaId: "sms" },
      { id: "calendar", label: "Marketing Calendar", quantity: 1, quotaId: "calendar" },
      { id: "video", label: "Video Scripts", quantity: 3, quotaId: "video" },
      { id: "strategy-session", label: "Quarterly Strategy Session", quantity: 1 },
      { id: "priority-queue", label: "Priority Production Queue", quantity: 1 },
    ],
    pricing: { display: "$799 per month", amountUsd: 799, billing: "monthly" },
    estimatedProductionTime: {
      customerLabel: "First concepts delivered within 7 business days",
      businessDays: 7,
    },
    productionEffort: { tier: "high", hoursEstimate: 32 },
    ...withDiscoverySync([
      { signal: "need", value: "better-business-systems", weight: 2 },
      { signal: "need", value: "workflow-improvements", weight: 2 },
      { signal: "situation", value: "Scaling operations", weight: 2 },
      { signal: "challenge", value: "Operations and efficiency", weight: 1 },
      { signal: "challenge", value: "Team and hiring", weight: 1 },
      { signal: "focus-keyword", value: "scale", tileId: "your-focus", weight: 2 },
      { signal: "focus-keyword", value: "system", tileId: "your-focus", weight: 2 },
    ]),
    productionNotes: "3 revision rounds included. Quarterly strategy session scheduled by ops.",
    status: "inactive",
  },
  {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    id: "email-marketing",
    familyId: "email_marketing",
    name: "Email Marketing",
    category: "email-marketing",
    customerProblemSolved: "Expanded email campaign copy beyond your base package.",
    customerReceives: "Additional email campaign copy aligned to base package timeline.",
    serviceClass: "essential",
    dependencies: ["spark"],
    includedRevisionRounds: 1,
    canSubstitute: false,
    addOnEligible: true,
    upgradeEligible: false,
    deliveryFormats: ["email-sequence"],
    minimumCustomerRequirements: ["Active SPARK or compatible base package"],
    recommendedCustomerRequirements: ["Email platform access for deployment"],
    internalProductionNotes: "Price TBD — placeholder until payment integration reads catalog.",
    serviceStatus: "retired",
    billingType: "one_time",
    priceCents: 0,
    productionLane: "standard_build",
    firstReviewWindow: STANDARD_FIRST,
    finalDeliveryWindow: STANDARD_FINAL,
    purpose: "Retired add-on — see Email Campaign Build (em-001).",
    deliverables: [],
    exclusions: [],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [],
    executionMode: "managed_execution_when_selected",
    requiresClientAccess: true,
    requiresClientMaterials: true,
    isRecommendable: false,
    isAddable: false,
    launchStatus: "retired",
    serviceGuideFaq: [],
    deliveryMapping: { fulfillmentMode: "project", executionChannel: "email", items: [] },
    customerDescription: "Expanded email campaign copy beyond your base package.",
    internalDescription: "Add-on — promotes email-campaign deliverable when customer opts in.",
    legacyDeliverables: [{ id: "email-campaign", label: "Email Campaign", quantity: 1 }],
    pricing: { display: "Quoted at checkout", amountUsd: 0, billing: "one-time" },
    estimatedProductionTime: {
      customerLabel: "Added to base package timeline",
      businessDays: 2,
    },
    productionEffort: { tier: "low", hoursEstimate: 3 },
    ...withDiscoverySync([
      { signal: "need", value: "improve-communication", weight: 2 },
      { signal: "need", value: "better-customer-experience", weight: 1 },
      { signal: "challenge", value: "Marketing and visibility", weight: 1 },
    ]),
    productionNotes: "Price TBD — placeholder until payment integration reads catalog.",
    status: "inactive",
  },
  {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    id: "sms-campaign",
    familyId: "sms_marketing",
    name: "SMS Campaign",
    category: "sms-marketing",
    customerProblemSolved: "SMS messaging copy to reach customers on mobile.",
    customerReceives: "SMS messaging copy bundle for mobile outreach.",
    serviceClass: "essential",
    dependencies: ["spark"],
    includedRevisionRounds: 1,
    canSubstitute: false,
    addOnEligible: true,
    upgradeEligible: false,
    deliveryFormats: ["sms-messages"],
    minimumCustomerRequirements: ["Active SPARK or compatible base package", "SMS opt-in compliance"],
    recommendedCustomerRequirements: ["SMS platform or provider configured"],
    serviceStatus: "retired",
    billingType: "one_time",
    priceCents: 0,
    productionLane: "quick_turn",
    firstReviewWindow: QUICK_FIRST,
    finalDeliveryWindow: QUICK_FINAL,
    purpose: "Retired add-on — see SMS Campaign Build (sms-001).",
    deliverables: [],
    exclusions: [],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [],
    executionMode: "managed_execution_when_selected",
    requiresClientAccess: true,
    requiresClientMaterials: false,
    isRecommendable: false,
    isAddable: false,
    launchStatus: "retired",
    serviceGuideFaq: [],
    deliveryMapping: { fulfillmentMode: "project", executionChannel: "sms", items: [] },
    customerDescription: "SMS messaging copy to reach customers on mobile.",
    internalDescription: "Add-on — promotes sms-messaging deliverable when customer opts in.",
    legacyDeliverables: [{ id: "sms-messaging", label: "SMS Messaging", quantity: 1 }],
    pricing: { display: "Quoted at checkout", amountUsd: 0, billing: "one-time" },
    estimatedProductionTime: {
      customerLabel: "Added to base package timeline",
      businessDays: 1,
    },
    productionEffort: { tier: "low", hoursEstimate: 2 },
    ...withDiscoverySync([
      { signal: "need", value: "improve-communication", weight: 2 },
      { signal: "need", value: "better-customer-experience", weight: 2 },
    ]),
    status: "inactive",
  },
  {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    id: "business-workflow",
    familyId: "campaign",
    name: "Business Workflow",
    category: "planning-strategy",
    customerProblemSolved: "Campaign planning and workflow documentation for your team.",
    customerReceives: "Campaign planning documentation and workflow guidance.",
    serviceClass: "core",
    dependencies: ["momentum"],
    includedRevisionRounds: 1,
    canSubstitute: false,
    addOnEligible: true,
    upgradeEligible: false,
    deliveryFormats: ["workflow-documentation"],
    minimumCustomerRequirements: ["Active MOMENTUM or compatible recurring package"],
    recommendedCustomerRequirements: ["Internal team roles defined for campaign execution"],
    serviceStatus: "retired",
    billingType: "one_time",
    priceCents: 0,
    productionLane: "standard_build",
    firstReviewWindow: STANDARD_FIRST,
    finalDeliveryWindow: STANDARD_FINAL,
    purpose: "Retired add-on.",
    deliverables: [],
    exclusions: [],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [],
    executionMode: "strategy_direction",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: false,
    isAddable: false,
    launchStatus: "retired",
    serviceGuideFaq: [],
    deliveryMapping: { fulfillmentMode: "project", items: [] },
    customerDescription: "Campaign planning and workflow documentation for your team.",
    internalDescription: "Add-on — promotes campaign-planning deliverable.",
    legacyDeliverables: [{ id: "campaign-planning", label: "Campaign Planning", quantity: 1 }],
    pricing: { display: "Quoted at checkout", amountUsd: 0, billing: "one-time" },
    estimatedProductionTime: {
      customerLabel: "Added to base package timeline",
      businessDays: 3,
    },
    productionEffort: { tier: "medium", hoursEstimate: 5 },
    ...withDiscoverySync([
      { signal: "need", value: "better-business-systems", weight: 2 },
      { signal: "need", value: "workflow-improvements", weight: 3 },
      { signal: "challenge", value: "Operations and efficiency", weight: 2 },
    ]),
    status: "inactive",
  },
  {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    id: "customer-follow-up",
    familyId: "campaign",
    name: "Customer Follow-Up",
    category: "campaign-services",
    customerProblemSolved: "Follow-up messaging sequences to nurture leads and customers.",
    customerReceives: "Cross-channel follow-up email and SMS copy sequences.",
    serviceClass: "core",
    dependencies: ["spark"],
    includedRevisionRounds: 1,
    canSubstitute: false,
    addOnEligible: true,
    upgradeEligible: false,
    deliveryFormats: ["follow-up-sequence", "email-sequence", "sms-messages"],
    minimumCustomerRequirements: ["Active SPARK or compatible base package"],
    recommendedCustomerRequirements: ["Lead capture or CRM workflow in place"],
    serviceStatus: "retired",
    billingType: "one_time",
    priceCents: 0,
    productionLane: "standard_build",
    firstReviewWindow: STANDARD_FIRST,
    finalDeliveryWindow: STANDARD_FINAL,
    purpose: "Retired add-on.",
    deliverables: [],
    exclusions: [],
    revisionRule: REVISION_ONE_TIME,
    clientResponsibilities: [],
    executionMode: "creation_delivery",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: false,
    isAddable: false,
    launchStatus: "retired",
    serviceGuideFaq: [],
    deliveryMapping: { fulfillmentMode: "project", items: [] },
    customerDescription: "Follow-up messaging sequences to nurture leads and customers.",
    internalDescription: "Add-on — cross-channel follow-up copy bundle.",
    legacyDeliverables: [
      { id: "email-campaign", label: "Follow-Up Emails", quantity: 3 },
      { id: "sms-messaging", label: "Follow-Up SMS", quantity: 3 },
    ],
    pricing: { display: "Quoted at checkout", amountUsd: 0, billing: "one-time" },
    estimatedProductionTime: {
      customerLabel: "Added to base package timeline",
      businessDays: 3,
    },
    productionEffort: { tier: "medium", hoursEstimate: 6 },
    ...withDiscoverySync([
      { signal: "need", value: "better-customer-experience", weight: 3 },
      { signal: "challenge", value: "Marketing and visibility", weight: 1 },
    ]),
    status: "inactive",
  },
  {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    id: "monthly-support",
    familyId: "campaign",
    name: "Monthly Support",
    category: "add-on-services",
    customerProblemSolved: "Ongoing Studio support beyond a one-time campaign.",
    customerReceives: "Ongoing marketing calendar and monthly production alignment.",
    serviceClass: "core",
    dependencies: ["spark"],
    includedRevisionRounds: 1,
    canSubstitute: ["momentum"],
    addOnEligible: true,
    upgradeEligible: true,
    deliveryFormats: ["marketing-calendar", "campaign-package"],
    minimumCustomerRequirements: ["Completed or active SPARK campaign"],
    recommendedCustomerRequirements: ["Interest in recurring monthly marketing"],
    internalProductionNotes: "Bridge add-on — signals upgrade path toward MOMENTUM.",
    serviceStatus: "retired",
    billingType: "monthly",
    priceCents: 0,
    productionLane: "ongoing_monthly",
    firstReviewWindow: STANDARD_FIRST,
    monthlyCycleWindow: {
      label: "Ongoing — aligned with monthly cycle",
    },
    purpose: "Retired add-on — see Monthly Campaign Support (cp-001-monthly).",
    deliverables: [],
    exclusions: [],
    revisionRule: REVISION_MONTHLY,
    clientResponsibilities: [],
    executionMode: "strategy_direction",
    requiresClientAccess: false,
    requiresClientMaterials: true,
    isRecommendable: false,
    isAddable: false,
    launchStatus: "retired",
    serviceGuideFaq: [],
    deliveryMapping: { fulfillmentMode: "monthly_cycle", items: [] },
    customerDescription: "Ongoing Studio support beyond a one-time campaign.",
    internalDescription: "Bridge add-on — signals upgrade path toward MOMENTUM.",
    legacyDeliverables: [{ id: "marketing-calendar", label: "Marketing Calendar", quantity: 1 }],
    pricing: { display: "Quoted at checkout", amountUsd: 0, billing: "monthly" },
    estimatedProductionTime: {
      customerLabel: "Ongoing — aligned with monthly cycle",
      businessDays: 7,
    },
    productionEffort: { tier: "medium", hoursEstimate: 8 },
    ...withDiscoverySync([
      { signal: "situation", value: "Growing an existing business", weight: 2 },
      { signal: "focus-keyword", value: "ongoing", tileId: "your-focus", weight: 2 },
      { signal: "focus-keyword", value: "support", tileId: "your-focus", weight: 1 },
    ]),
    status: "inactive",
  },
] as const;

/** Temporary raw assembly — normalized at export via `@/catalog/seeds`. */
export const RAW_SERVICE_CATALOG: readonly StudioServiceEntry[] = [
  ...V2_LAUNCH_SERVICES,
  ...LEGACY_RETIRED_SERVICES,
] as const;
