import type {
  KitchenAuditEvent,
  KitchenCampaign,
  KitchenDeliverableLine,
  KitchenTimestamp,
} from "@/config/studio-kitchen";
import type {
  KitchenExceptionTrayId,
  KitchenFileBucketId,
} from "@/config/studio-kitchen-file-room";

const ts = (date: string, time: string): KitchenTimestamp => ({ date, time });

export const KITCHEN_CLIENT_DELAY_DAYS = 7;

export function kitchenDefaultDeliverables(complete = 0): KitchenDeliverableLine[] {
  const totals = { SOCIAL: 6, EMAIL: 6, SMS: 6, CALENDAR: 1, VIDEO: 2 } as const;
  return (Object.keys(totals) as KitchenDeliverableLine["key"][]).map((key) => ({
    key,
    complete: key === "SOCIAL" || key === "EMAIL" ? complete : 0,
    total: totals[key],
  }));
}

export function kitchenProductionDeliverables(
  overrides: Partial<Record<KitchenDeliverableLine["key"], { complete: number; total?: number }>>,
): KitchenDeliverableLine[] {
  const base = kitchenDefaultDeliverables(0);
  return base.map((line) => {
    const override = overrides[line.key];
    if (!override) return line;
    return {
      key: line.key,
      complete: override.complete,
      total: override.total ?? line.total,
    };
  });
}

type CampaignSeed = KitchenCampaign;

function campaign(seed: CampaignSeed): KitchenCampaign {
  return seed;
}

function inBucket(
  homeBucketId: KitchenFileBucketId,
  queueOrder: number,
  extra?: Partial<KitchenCampaign>,
): Pick<KitchenCampaign, "folderLocation" | "homeBucketId" | "queueOrder"> & Partial<KitchenCampaign> {
  return { folderLocation: "bucket", homeBucketId, queueOrder, ...extra };
}

function inTray(
  trayId: KitchenExceptionTrayId,
  homeBucketId: KitchenFileBucketId,
  extra?: Partial<KitchenCampaign>,
): Pick<KitchenCampaign, "folderLocation" | "trayId" | "homeBucketId"> & Partial<KitchenCampaign> {
  return { folderLocation: "tray", trayId, homeBucketId, ...extra };
}

/** Phase 1 seed — file room placements with queue re-entry rules */
export const kitchenCampaignSeed: KitchenCampaign[] = [
  campaign({
    id: "studio-marketing-membership",
    folderNumber: "ST-2026-001",
    ...inBucket("intake-received", 1),
    campaignName: "Studio Marketing Membership",
    clientName: "Team Studio",
    currentStageId: "new-campaign",
    assignedTo: "Tagia",
    waitingOn: "Campaign Brief",
    daysInStage: 1,
    statusLabel: "Campaign Brief Needed",
    nextAction: "Awaiting Production Start",
    priority: "Normal",
    stageEnteredAt: ts("June 20, 2026", "9:30 AM"),
    lastUpdated: ts("June 21, 2026", "8:10 AM"),
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenDefaultDeliverables(0),
    ownerNotes: ["Internal membership campaign — prioritize clarity over volume."],
    history: [],
    auditTrail: [
      { label: "Campaign Submitted", timestamp: ts("June 20, 2026", "9:30 AM"), responsible: "Team Studio" },
    ],
    alerts: { waitingOnOwner: true },
  }),
  campaign({
    id: "spring-launch",
    folderNumber: "ST-2026-002",
    ...inBucket("intake-received", 2),
    campaignName: "Spring Launch",
    clientName: "Bloom & Co",
    currentStageId: "new-campaign",
    assignedTo: "Tagia",
    waitingOn: "Tagia",
    daysInStage: 2,
    statusLabel: "Campaign Brief Needed",
    nextAction: "Awaiting Production Start",
    priority: "Rush",
    stageEnteredAt: ts("June 19, 2026", "2:00 PM"),
    lastUpdated: ts("June 21, 2026", "7:45 AM"),
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenDefaultDeliverables(0),
    ownerNotes: ["Client requested warmer tone.", "Launch date is firm — treat as rush."],
    auditTrail: [
      { label: "Campaign Submitted", timestamp: ts("June 19, 2026", "2:00 PM"), responsible: "Bloom & Co" },
    ],
    alerts: { waitingOnOwner: true },
  }),
  campaign({
    id: "local-seo-push",
    folderNumber: "ST-2026-003",
    ...inBucket("needs-concepts", 1),
    campaignName: "Local SEO Push",
    clientName: "Harbor Dental",
    currentStageId: "needs-directions",
    assignedTo: "Tagia",
    waitingOn: "Tagia",
    daysInStage: 1,
    statusLabel: "Concepts Needed",
    nextAction: "View Campaign Brief",
    priority: "Normal",
    stageEnteredAt: ts("June 20, 2026", "11:00 AM"),
    lastUpdated: ts("June 21, 2026", "10:20 AM"),
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenDefaultDeliverables(0),
    ownerNotes: [],
    auditTrail: [
      { label: "Campaign Submitted", timestamp: ts("June 18, 2026", "3:15 PM"), responsible: "Harbor Dental" },
      { label: "Directions Requested", timestamp: ts("June 20, 2026", "11:00 AM"), responsible: "Tagia" },
    ],
    alerts: { waitingOnOwner: true },
  }),
  campaign({
    id: "grand-opening",
    folderNumber: "ST-2026-004",
    ...inBucket("needs-concepts", 2),
    campaignName: "Grand Opening",
    clientName: "River Cafe",
    currentStageId: "needs-directions",
    assignedTo: "Tagia",
    waitingOn: "Tagia",
    daysInStage: 3,
    statusLabel: "Concepts Needed",
    nextAction: "Copy Campaign Brief",
    priority: "Waiting",
    stageEnteredAt: ts("June 18, 2026", "4:30 PM"),
    lastUpdated: ts("June 21, 2026", "9:00 AM"),
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenDefaultDeliverables(0),
    ownerNotes: ["Wants stronger CTA on direction concepts."],
    auditTrail: [
      { label: "Campaign Submitted", timestamp: ts("June 16, 2026", "1:00 PM"), responsible: "River Cafe" },
      { label: "Directions Requested", timestamp: ts("June 18, 2026", "4:30 PM"), responsible: "Tagia" },
    ],
    alerts: { waitingOnOwner: true },
  }),
  campaign({
    id: "membership-drive",
    folderNumber: "ST-2026-005",
    ...inBucket("needs-concepts", 3),
    campaignName: "Membership Drive",
    clientName: "FitHouse Gym",
    currentStageId: "needs-directions",
    assignedTo: "ChatGPT",
    waitingOn: "ChatGPT",
    daysInStage: 2,
    statusLabel: "Concepts In Progress",
    nextAction: "Awaiting Direction Selection",
    priority: "Normal",
    stageEnteredAt: ts("June 19, 2026", "10:00 AM"),
    lastUpdated: ts("June 20, 2026", "5:30 PM"),
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenDefaultDeliverables(0),
    ownerNotes: [],
    auditTrail: [
      { label: "Campaign Submitted", timestamp: ts("June 17, 2026", "9:00 AM"), responsible: "FitHouse Gym" },
      { label: "Directions Requested", timestamp: ts("June 19, 2026", "10:00 AM"), responsible: "Tagia" },
    ],
  }),
  campaign({
    id: "brand-awareness-joes-auto",
    folderNumber: "ST-2026-006",
    ...inBucket("client-reviewing-concepts", 1),
    campaignName: "Brand Awareness",
    clientName: "Joe's Auto",
    currentStageId: "waiting-on-client",
    assignedTo: "Client",
    waitingOn: "Client",
    daysInStage: 3,
    statusLabel: "Client Reviewing Concepts",
    nextAction: "View Selected Concept",
    priority: "Waiting",
    stageEnteredAt: ts("June 18, 2026", "4:15 PM"),
    lastUpdated: ts("June 21, 2026", "4:15 PM"),
    reviewNoticeSent: ts("June 18, 2026", "4:15 PM"),
    lastContactDate: ts("June 21, 2026", "10:00 AM"),
    reminderCount: "1 of 3",
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenDefaultDeliverables(0),
    ownerNotes: [],
    auditTrail: [
      { label: "Campaign Submitted", timestamp: ts("June 12, 2026", "11:00 AM"), responsible: "Joe's Auto" },
      { label: "Directions Delivered", timestamp: ts("June 17, 2026", "2:30 PM"), responsible: "ChatGPT" },
      { label: "Client Review Sent", timestamp: ts("June 18, 2026", "4:15 PM"), responsible: "Tagia" },
    ],
  }),
  campaign({
    id: "summer-promo",
    folderNumber: "ST-2026-007",
    ...inTray("client-delayed", "client-reviewing-concepts"),
    campaignName: "Summer Promo",
    clientName: "Sunny Pools",
    currentStageId: "waiting-on-client",
    assignedTo: "Client",
    waitingOn: "Client",
    daysInStage: 12,
    statusLabel: "Client Delayed",
    nextAction: "Paused — awaiting client response",
    priority: "Client Delayed",
    stageEnteredAt: ts("June 9, 2026", "1:00 PM"),
    lastUpdated: ts("June 20, 2026", "3:00 PM"),
    reviewNoticeSent: ts("June 9, 2026", "1:00 PM"),
    lastContactDate: ts("June 24, 2026", "9:30 AM"),
    reminderCount: "2 of 3",
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenDefaultDeliverables(0),
    ownerNotes: ["Client went quiet after second reminder."],
    auditTrail: [
      { label: "Campaign Submitted", timestamp: ts("June 5, 2026", "9:00 AM"), responsible: "Sunny Pools" },
      { label: "Client Review Sent", timestamp: ts("June 9, 2026", "1:00 PM"), responsible: "Tagia" },
      { label: "Moved To Client Delayed Tray", timestamp: ts("June 17, 2026", "9:00 AM"), responsible: "Tagia" },
    ],
    alerts: { clientStalled: true },
  }),
  campaign({
    id: "holiday-catalog",
    folderNumber: "ST-2026-008",
    ...inTray("client-delayed", "client-reviewing-concepts"),
    campaignName: "Holiday Catalog",
    clientName: "Artisan Gifts",
    currentStageId: "waiting-on-client",
    assignedTo: "Client",
    waitingOn: "Client",
    daysInStage: 4,
    statusLabel: "Client Delayed",
    nextAction: "Paused — awaiting client response",
    priority: "Client Delayed",
    stageEnteredAt: ts("June 17, 2026", "9:00 AM"),
    lastUpdated: ts("June 21, 2026", "12:00 PM"),
    reviewNoticeSent: ts("June 17, 2026", "9:00 AM"),
    lastContactDate: ts("June 21, 2026", "12:00 PM"),
    reminderCount: "0 of 3",
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenDefaultDeliverables(0),
    ownerNotes: [],
    auditTrail: [
      { label: "Client Review Sent", timestamp: ts("June 17, 2026", "9:00 AM"), responsible: "Tagia" },
      { label: "Moved To Client Delayed Tray", timestamp: ts("June 18, 2026", "2:00 PM"), responsible: "Tagia" },
    ],
    alerts: { clientStalled: true },
  }),
  campaign({
    id: "rebrand-launch",
    folderNumber: "ST-2026-009",
    ...inBucket("client-reviewing-concepts", 3, {
      returnedToQueueAt: ts("June 21, 2026", "8:45 AM"),
    }),
    campaignName: "Rebrand Launch",
    clientName: "Northline Law",
    currentStageId: "waiting-on-client",
    assignedTo: "Client",
    waitingOn: "Client",
    daysInStage: 2,
    statusLabel: "Returned To Queue",
    nextAction: "Awaiting Deliverable Approval",
    priority: "Waiting",
    stageEnteredAt: ts("June 21, 2026", "8:45 AM"),
    lastUpdated: ts("June 21, 2026", "8:45 AM"),
    reviewNoticeSent: ts("June 13, 2026", "10:30 AM"),
    lastContactDate: ts("June 21, 2026", "8:30 AM"),
    reminderCount: "0 of 3",
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenDefaultDeliverables(0),
    ownerNotes: ["Client responded — re-entered at back of queue per Kitchen rule."],
    auditTrail: [
      { label: "Client Review Sent", timestamp: ts("June 13, 2026", "10:30 AM"), responsible: "Tagia" },
      { label: "Moved To Client Delayed Tray", timestamp: ts("June 14, 2026", "10:00 AM"), responsible: "Tagia" },
      { label: "Returned To Active Queue", timestamp: ts("June 21, 2026", "8:45 AM"), responsible: "Tagia" },
    ],
  }),
  campaign({
    id: "product-spotlight",
    folderNumber: "ST-2026-010",
    ...inBucket("in-production", 1),
    campaignName: "Product Spotlight",
    clientName: "GreenLeaf Organics",
    currentStageId: "in-production",
    assignedTo: "ChatGPT",
    waitingOn: "ChatGPT",
    daysInStage: 4,
    statusLabel: "Building Deliverables",
    nextAction: "View Production Brief",
    priority: "Normal",
    stageEnteredAt: ts("June 17, 2026", "8:00 AM"),
    lastUpdated: ts("June 21, 2026", "1:30 PM"),
    selectedDirection: "Direction B",
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenProductionDeliverables({
      SOCIAL: { complete: 6 },
      EMAIL: { complete: 6 },
      SMS: { complete: 3 },
      CALENDAR: { complete: 0 },
      VIDEO: { complete: 1 },
    }),
    ownerNotes: ["SMS batch delayed — waiting on product shots."],
    auditTrail: [
      { label: "Direction C Selected", timestamp: ts("June 16, 2026", "3:00 PM"), responsible: "Tagia" },
      { label: "Production Started", timestamp: ts("June 17, 2026", "8:00 AM"), responsible: "ChatGPT" },
    ],
  }),
  campaign({
    id: "community-event",
    folderNumber: "ST-2026-011",
    ...inBucket("in-production", 2),
    campaignName: "Community Event",
    clientName: "Main Street Collective",
    currentStageId: "in-production",
    assignedTo: "ChatGPT",
    waitingOn: "ChatGPT",
    daysInStage: 2,
    statusLabel: "Building Deliverables",
    nextAction: "Paste Deliverables",
    priority: "Rush",
    stageEnteredAt: ts("June 19, 2026", "2:00 PM"),
    lastUpdated: ts("June 21, 2026", "11:00 AM"),
    selectedDirection: "Direction A",
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenProductionDeliverables({
      SOCIAL: { complete: 4, total: 6 },
      EMAIL: { complete: 6, total: 6 },
      SMS: { complete: 6, total: 6 },
      CALENDAR: { complete: 1, total: 1 },
      VIDEO: { complete: 0, total: 2 },
    }),
    ownerNotes: [],
    auditTrail: [
      { label: "Production Started", timestamp: ts("June 19, 2026", "2:00 PM"), responsible: "ChatGPT" },
    ],
  }),
  campaign({
    id: "email-nurture",
    folderNumber: "ST-2026-012",
    ...inTray("client-delayed", "client-reviewing-deliverables"),
    campaignName: "Email Nurture Series",
    clientName: "Peak Consulting",
    currentStageId: "ready-for-client-review",
    assignedTo: "Client",
    waitingOn: "Client",
    daysInStage: 10,
    statusLabel: "Client Delayed",
    nextAction: "Paused — awaiting client review",
    priority: "Client Delayed",
    stageEnteredAt: ts("June 11, 2026", "5:00 PM"),
    lastUpdated: ts("June 20, 2026", "2:00 PM"),
    reviewNoticeSent: ts("June 11, 2026", "5:00 PM"),
    lastContactDate: ts("June 18, 2026", "9:00 AM"),
    reminderCount: "2 of 3",
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenProductionDeliverables({
      SOCIAL: { complete: 6 },
      EMAIL: { complete: 6 },
      SMS: { complete: 6 },
      CALENDAR: { complete: 1 },
      VIDEO: { complete: 2 },
    }),
    ownerNotes: [],
    auditTrail: [
      { label: "Production Started", timestamp: ts("June 15, 2026", "10:00 AM"), responsible: "ChatGPT" },
      { label: "Owner Review Complete", timestamp: ts("June 20, 2026", "4:30 PM"), responsible: "Tagia" },
      { label: "Moved To Client Delayed Tray", timestamp: ts("June 19, 2026", "9:00 AM"), responsible: "Tagia" },
    ],
    alerts: { clientStalled: true },
  }),
  campaign({
    id: "social-refresh",
    folderNumber: "ST-2026-013",
    ...inBucket("revision-queue", 1),
    campaignName: "Social Refresh",
    clientName: "Coastal Realty",
    currentStageId: "revision-requests",
    assignedTo: "Tagia",
    waitingOn: "Revision Notes",
    daysInStage: 5,
    statusLabel: "Revision Requested",
    nextAction: "View Revision Notes",
    priority: "Overdue",
    stageEnteredAt: ts("June 16, 2026", "9:00 AM"),
    lastUpdated: ts("June 20, 2026", "4:00 PM"),
    revisionsUsed: 1,
    revisionsTotal: 3,
    deliverables: kitchenProductionDeliverables({
      SOCIAL: { complete: 5, total: 6 },
      EMAIL: { complete: 6, total: 6 },
      SMS: { complete: 6, total: 6 },
      CALENDAR: { complete: 1, total: 1 },
      VIDEO: { complete: 2, total: 2 },
    }),
    ownerNotes: ["Requested additional revisions on social tone.", "Client wants stronger CTA."],
    auditTrail: [
      { label: "Revision Round 1", timestamp: ts("June 16, 2026", "9:00 AM"), responsible: "Coastal Realty" },
      { label: "Client Review Sent", timestamp: ts("June 14, 2026", "3:00 PM"), responsible: "Tagia" },
    ],
    alerts: { revisionOverdue: true, waitingOnOwner: true },
  }),
  campaign({
    id: "webinar-push",
    folderNumber: "ST-2026-014",
    ...inBucket("owner-review", 1),
    campaignName: "Webinar Push",
    clientName: "LearnLab",
    currentStageId: "owner-review",
    assignedTo: "Tagia",
    waitingOn: "Tagia",
    daysInStage: 1,
    statusLabel: "Owner Quality Check",
    nextAction: "Approve Deliverables",
    priority: "Rush",
    stageEnteredAt: ts("June 20, 2026", "3:00 PM"),
    lastUpdated: ts("June 21, 2026", "3:30 PM"),
    revisionsUsed: 2,
    revisionsTotal: 3,
    deliverables: kitchenProductionDeliverables({
      SOCIAL: { complete: 6 },
      EMAIL: { complete: 6 },
      SMS: { complete: 4, total: 6 },
      CALENDAR: { complete: 1 },
      VIDEO: { complete: 2 },
    }),
    ownerNotes: [],
    auditTrail: [
      { label: "Production Started", timestamp: ts("June 18, 2026", "11:00 AM"), responsible: "ChatGPT" },
    ],
    alerts: { deliverablesReadyForReview: true, waitingOnOwner: true },
  }),
  campaign({
    id: "loyalty-program",
    folderNumber: "ST-2026-015",
    ...inBucket("production-ready", 1),
    campaignName: "Loyalty Program",
    clientName: "Bean & Brew",
    currentStageId: "ready-for-production",
    assignedTo: "Tagia",
    waitingOn: "Tagia",
    daysInStage: 1,
    statusLabel: "Production Ready",
    nextAction: "Copy Production Brief",
    priority: "Normal",
    stageEnteredAt: ts("June 20, 2026", "1:00 PM"),
    lastUpdated: ts("June 21, 2026", "10:00 AM"),
    selectedDirection: "Direction C",
    revisionsUsed: 3,
    revisionsTotal: 3,
    deliverables: kitchenDefaultDeliverables(0),
    ownerNotes: ["All revisions used on prior round — locked."],
    auditTrail: [
      { label: "Direction C Selected", timestamp: ts("June 20, 2026", "12:45 PM"), responsible: "Bean & Brew" },
    ],
    alerts: { waitingOnOwner: true },
  }),
  campaign({
    id: "summer-service-special",
    folderNumber: "ST-2026-016",
    ...inBucket("final-delivery", 1),
    campaignName: "Summer Service Special",
    clientName: "Joe's Auto",
    currentStageId: "final-delivery",
    assignedTo: "Tagia",
    waitingOn: "Tagia",
    daysInStage: 1,
    statusLabel: "Final Delivery Ready",
    nextAction: "Publish Final Delivery",
    priority: "Normal",
    stageEnteredAt: ts("June 20, 2026", "4:00 PM"),
    lastUpdated: ts("June 21, 2026", "4:30 PM"),
    revisionsUsed: 1,
    revisionsTotal: 3,
    deliverables: kitchenProductionDeliverables({
      SOCIAL: { complete: 6 },
      EMAIL: { complete: 6 },
      SMS: { complete: 6 },
      CALENDAR: { complete: 1 },
      VIDEO: { complete: 2 },
    }),
    ownerNotes: [],
    auditTrail: [
      { label: "Client Approved Deliverables", timestamp: ts("June 20, 2026", "3:30 PM"), responsible: "Joe's Auto" },
      { label: "Final Package Ready", timestamp: ts("June 20, 2026", "4:00 PM"), responsible: "Tagia" },
    ],
    alerts: { waitingOnOwner: true },
  }),
  campaign({
    id: "artisan-gifts-deliverables",
    folderNumber: "ST-2026-017",
    ...inBucket("client-reviewing-deliverables", 1),
    campaignName: "Holiday Catalog",
    clientName: "Artisan Gifts",
    currentStageId: "ready-for-client-review",
    assignedTo: "Client",
    waitingOn: "Client",
    daysInStage: 2,
    statusLabel: "Client Reviewing Deliverables",
    nextAction: "Awaiting client approval",
    priority: "Waiting",
    stageEnteredAt: ts("June 19, 2026", "9:00 AM"),
    lastUpdated: ts("June 21, 2026", "12:00 PM"),
    reviewNoticeSent: ts("June 19, 2026", "9:00 AM"),
    lastContactDate: ts("June 21, 2026", "12:00 PM"),
    reminderCount: "0 of 3",
    revisionsUsed: 0,
    revisionsTotal: 3,
    deliverables: kitchenProductionDeliverables({
      SOCIAL: { complete: 6 },
      EMAIL: { complete: 6 },
      SMS: { complete: 6 },
      CALENDAR: { complete: 1 },
      VIDEO: { complete: 2 },
    }),
    ownerNotes: [],
    auditTrail: [
      { label: "Owner Review Complete", timestamp: ts("June 19, 2026", "8:30 AM"), responsible: "Tagia" },
      { label: "Deliverables Sent To Client", timestamp: ts("June 19, 2026", "9:00 AM"), responsible: "Tagia" },
    ],
  }),
];
