-- STUDIO-OPERATING-WORK-SUPERVISION-AND-INCIDENT-ESCALATION-1
-- Pass 3B launch-runtime durability. Supabase Postgres record store.
-- Object/file storage is not this database.
-- Apply in the Supabase SQL editor or CLI as a server-side Owner step.
-- Do not expose the service-role key to the browser.

BEGIN;

CREATE TABLE IF NOT EXISTS supervision_leases (
  lease_id text PRIMARY KEY,
  customer_id text NOT NULL,
  project_id text NOT NULL,
  campaign_id text NOT NULL,
  health text NOT NULL,
  kind text NOT NULL,
  last_heartbeat_at timestamptz NOT NULL,
  last_healthy_at timestamptz,
  expected_update_at timestamptz,
  next_check_at timestamptz,
  payload jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS supervision_leases_tenant_idx
  ON supervision_leases (customer_id, project_id);
CREATE INDEX IF NOT EXISTS supervision_leases_heartbeat_idx
  ON supervision_leases (last_heartbeat_at);
CREATE INDEX IF NOT EXISTS supervision_leases_health_idx
  ON supervision_leases (health);
CREATE INDEX IF NOT EXISTS supervision_leases_next_check_idx
  ON supervision_leases (next_check_at);

CREATE TABLE IF NOT EXISTS supervision_incidents (
  incident_id text PRIMARY KEY,
  lease_id text,
  customer_id text NOT NULL,
  project_id text NOT NULL,
  campaign_id text NOT NULL,
  dedupe_key text NOT NULL,
  state text NOT NULL,
  severity text NOT NULL,
  owner_escalated boolean NOT NULL DEFAULT false,
  next_check_at timestamptz NOT NULL,
  payload jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS supervision_incidents_tenant_idx
  ON supervision_incidents (customer_id, project_id);
CREATE INDEX IF NOT EXISTS supervision_incidents_next_check_idx
  ON supervision_incidents (next_check_at);
CREATE UNIQUE INDEX IF NOT EXISTS supervision_incidents_open_dedupe_idx
  ON supervision_incidents (customer_id, dedupe_key)
  WHERE state <> 'RESOLVED';

CREATE TABLE IF NOT EXISTS supervision_incident_events (
  event_id text PRIMARY KEY,
  incident_id text NOT NULL REFERENCES supervision_incidents(incident_id),
  at timestamptz NOT NULL,
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  type text NOT NULL,
  actor text NOT NULL,
  summary text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  recorded_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS supervision_incident_events_incident_idx
  ON supervision_incident_events (incident_id, seq);

CREATE TABLE IF NOT EXISTS supervision_recovery_attempts (
  incident_id text NOT NULL REFERENCES supervision_incidents(incident_id),
  attempt_index integer NOT NULL,
  at timestamptz NOT NULL,
  strategy text NOT NULL,
  result text NOT NULL,
  detail text NOT NULL,
  PRIMARY KEY (incident_id, attempt_index)
);

CREATE TABLE IF NOT EXISTS supervision_idempotency (
  lease_id text NOT NULL,
  idempotency_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (lease_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS supervision_heartbeats (
  heartbeat_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lease_id text NOT NULL,
  idempotency_key text NOT NULL,
  at timestamptz NOT NULL,
  reported_status text,
  customer_id text NOT NULL,
  project_id text NOT NULL
);

CREATE INDEX IF NOT EXISTS supervision_heartbeats_lease_idx
  ON supervision_heartbeats (lease_id, at);

CREATE TABLE IF NOT EXISTS supervision_coverage (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  providers jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS supervision_sweep_claims (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  claim_id text NOT NULL,
  claimed_at timestamptz NOT NULL,
  holder text NOT NULL,
  expires_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS supervision_sweep_evaluations (
  evaluation_id text PRIMARY KEY,
  claim_id text NOT NULL,
  at timestamptz NOT NULL,
  lease_id text NOT NULL,
  incident_id text,
  health text NOT NULL
);

CREATE TABLE IF NOT EXISTS supervision_meta (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  schema_version integer NOT NULL DEFAULT 1,
  provider text NOT NULL DEFAULT 'supabase-postgres',
  restored_at timestamptz,
  last_sweep_claim jsonb
);

INSERT INTO supervision_meta (id, schema_version, provider)
VALUES (1, 1, 'supabase-postgres')
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE FUNCTION supervision_forbid_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'APPEND_ONLY_VIOLATION';
END;
$$;

DROP TRIGGER IF EXISTS supervision_incident_events_no_update ON supervision_incident_events;
CREATE TRIGGER supervision_incident_events_no_update
  BEFORE UPDATE OR DELETE ON supervision_incident_events
  FOR EACH ROW EXECUTE FUNCTION supervision_forbid_mutation();

DROP TRIGGER IF EXISTS supervision_heartbeats_no_update ON supervision_heartbeats;
CREATE TRIGGER supervision_heartbeats_no_update
  BEFORE UPDATE OR DELETE ON supervision_heartbeats
  FOR EACH ROW EXECUTE FUNCTION supervision_forbid_mutation();

DROP TRIGGER IF EXISTS supervision_sweep_evaluations_no_update ON supervision_sweep_evaluations;
CREATE TRIGGER supervision_sweep_evaluations_no_update
  BEFORE UPDATE OR DELETE ON supervision_sweep_evaluations
  FOR EACH ROW EXECUTE FUNCTION supervision_forbid_mutation();

CREATE OR REPLACE FUNCTION supervision_try_claim_sweep(
  p_claim_id text,
  p_holder text,
  p_at timestamptz,
  p_ttl_ms integer
)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  existing supervision_sweep_claims%ROWTYPE;
  next_expires timestamptz;
BEGIN
  next_expires := p_at + make_interval(secs => p_ttl_ms / 1000.0);
  SELECT * INTO existing FROM supervision_sweep_claims WHERE id = 1 FOR UPDATE;
  IF existing.id IS NOT NULL
     AND existing.expires_at > p_at
     AND existing.holder <> p_holder THEN
    RETURN jsonb_build_object(
      'claimed', false,
      'claim', jsonb_build_object(
        'claimId', existing.claim_id,
        'claimedAt', existing.claimed_at,
        'holder', existing.holder,
        'expiresAt', existing.expires_at
      )
    );
  END IF;
  INSERT INTO supervision_sweep_claims (id, claim_id, claimed_at, holder, expires_at)
  VALUES (1, p_claim_id, p_at, p_holder, next_expires)
  ON CONFLICT (id) DO UPDATE SET
    claim_id = EXCLUDED.claim_id,
    claimed_at = EXCLUDED.claimed_at,
    holder = EXCLUDED.holder,
    expires_at = EXCLUDED.expires_at;
  UPDATE supervision_meta
    SET last_sweep_claim = jsonb_build_object(
      'claimId', p_claim_id,
      'claimedAt', p_at,
      'holder', p_holder,
      'expiresAt', next_expires
    )
    WHERE id = 1;
  RETURN jsonb_build_object(
    'claimed', true,
    'claim', jsonb_build_object(
      'claimId', p_claim_id,
      'claimedAt', p_at,
      'holder', p_holder,
      'expiresAt', next_expires
    )
  );
END;
$$;

ALTER TABLE supervision_leases ENABLE ROW LEVEL SECURITY;
ALTER TABLE supervision_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE supervision_incident_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE supervision_recovery_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE supervision_idempotency ENABLE ROW LEVEL SECURITY;
ALTER TABLE supervision_heartbeats ENABLE ROW LEVEL SECURITY;
ALTER TABLE supervision_coverage ENABLE ROW LEVEL SECURITY;
ALTER TABLE supervision_sweep_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE supervision_sweep_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE supervision_meta ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE supervision_leases FROM anon, authenticated;
REVOKE ALL ON TABLE supervision_incidents FROM anon, authenticated;
REVOKE ALL ON TABLE supervision_incident_events FROM anon, authenticated;
REVOKE ALL ON TABLE supervision_recovery_attempts FROM anon, authenticated;
REVOKE ALL ON TABLE supervision_idempotency FROM anon, authenticated;
REVOKE ALL ON TABLE supervision_heartbeats FROM anon, authenticated;
REVOKE ALL ON TABLE supervision_coverage FROM anon, authenticated;
REVOKE ALL ON TABLE supervision_sweep_claims FROM anon, authenticated;
REVOKE ALL ON TABLE supervision_sweep_evaluations FROM anon, authenticated;
REVOKE ALL ON TABLE supervision_meta FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE supervision_leases TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE supervision_incidents TO service_role;
GRANT SELECT, INSERT ON TABLE supervision_incident_events TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE supervision_recovery_attempts TO service_role;
GRANT SELECT, INSERT ON TABLE supervision_idempotency TO service_role;
GRANT SELECT, INSERT ON TABLE supervision_heartbeats TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE supervision_coverage TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE supervision_sweep_claims TO service_role;
GRANT SELECT, INSERT ON TABLE supervision_sweep_evaluations TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE supervision_meta TO service_role;
GRANT EXECUTE ON FUNCTION supervision_try_claim_sweep(text, text, timestamptz, integer) TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
-- service_role bypasses RLS in Supabase. anon and authenticated remain revoked.

COMMIT;
